;; Copyright (c) 2010, Philipp Stephani <st_philipp@yahoo.de>
;;
;; Permission is hereby granted, free of charge, to any person obtaining a copy
;; of this software and associated documentation files (the "Software"), to
;; deal in the Software without restriction, including without limitation the
;; rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
;; sell copies of the Software, and to permit persons to whom the Software is
;; furnished to do so, subject to the following conditions:
;;
;; The above copyright notice and this permission notice shall be included in
;; all copies or substantial portions of the Software.
;;
;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
;; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
;; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
;; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
;; FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
;; IN THE SOFTWARE.

(TeX-add-style-hook
 "latex3-autogen"
 (function
  (lambda ()
    (TeX-add-symbols
     '("quark_new:N" TeX-arg-macro)
     '("quark_if_nil_p:N" TeX-arg-macro)
     '("quark_if_nil:NT" TeX-arg-macro "true code")
     '("quark_if_nil:NF" TeX-arg-macro "false code")
     '("quark_if_nil:NTF" TeX-arg-macro "true code" "false code")
     '("quark_if_nil_p:n" "arg1")
     '("quark_if_nil_p:V" TeX-arg-macro)
     '("quark_if_nil_p:o" TeX-arg-macro)
     '("quark_if_nil:nT" "tokens" "true code")
     '("quark_if_nil:nF" "tokens" "false code")
     '("quark_if_nil:nTF" "tokens" "true code" "false code")
     '("quark_if_nil:VT" TeX-arg-macro "arg2")
     '("quark_if_nil:VF" TeX-arg-macro "arg2")
     '("quark_if_nil:VTF" TeX-arg-macro "arg2" "arg3")
     '("quark_if_nil:oT" TeX-arg-macro "arg2")
     '("quark_if_nil:oF" TeX-arg-macro "arg2")
     '("quark_if_nil:oTF" TeX-arg-macro "arg2" "arg3")
     "q_recursion_tail"
     "q_recursion_stop"
     "q_no_value"
     "q_stop"
     "q_nil"
     "q_error"
     "q_mark"
     '("token_new:Nn" TeX-arg-macro "token 2")
     '("token_if_group_begin_p:N" TeX-arg-macro)
     '("token_if_group_begin:NT" TeX-arg-macro "true")
     '("token_if_group_begin:NF" TeX-arg-macro "false")
     '("token_if_group_begin:NTF" TeX-arg-macro "true" "false")
     '("token_if_group_end_p:N" TeX-arg-macro)
     '("token_if_group_end:NT" TeX-arg-macro "true")
     '("token_if_group_end:NF" TeX-arg-macro "false")
     '("token_if_group_end:NTF" TeX-arg-macro "true" "false")
     '("token_if_math_shift_p:N" TeX-arg-macro)
     '("token_if_math_shift:NT" TeX-arg-macro "true")
     '("token_if_math_shift:NF" TeX-arg-macro "false")
     '("token_if_math_shift:NTF" TeX-arg-macro "true" "false")
     '("token_if_alignment_tab_p:N" TeX-arg-macro)
     '("token_if_alignment_tab:NT" TeX-arg-macro "arg2")
     '("token_if_alignment_tab:NF" TeX-arg-macro "arg2")
     '("token_if_alignment_tab:NTF" TeX-arg-macro "arg2" "arg3")
     '("token_if_parameter_p:N" TeX-arg-macro)
     '("token_if_parameter:NT" TeX-arg-macro "true")
     '("token_if_parameter:NF" TeX-arg-macro "false")
     '("token_if_parameter:NTF" TeX-arg-macro "true" "false")
     '("token_if_math_superscript_p:N" TeX-arg-macro)
     '("token_if_math_superscript:NT" TeX-arg-macro "true")
     '("token_if_math_superscript:NF" TeX-arg-macro "false")
     '("token_if_math_superscript:NTF" TeX-arg-macro "true" "false")
     '("token_if_math_subscript_p:N" TeX-arg-macro)
     '("token_if_math_subscript:NT" TeX-arg-macro "true")
     '("token_if_math_subscript:NF" TeX-arg-macro "false")
     '("token_if_math_subscript:NTF" TeX-arg-macro "true" "false")
     '("token_if_space_p:N" TeX-arg-macro)
     '("token_if_space:NT" TeX-arg-macro "true")
     '("token_if_space:NF" TeX-arg-macro "false")
     '("token_if_space:NTF" TeX-arg-macro "true" "false")
     '("token_if_letter_p:N" TeX-arg-macro)
     '("token_if_letter:NT" TeX-arg-macro "true")
     '("token_if_letter:NF" TeX-arg-macro "false")
     '("token_if_letter:NTF" TeX-arg-macro "true" "false")
     '("token_if_other_char_p:N" TeX-arg-macro)
     '("token_if_other_char:NT" TeX-arg-macro "true")
     '("token_if_other_char:NF" TeX-arg-macro "false")
     '("token_if_other_char:NTF" TeX-arg-macro "true" "false")
     '("token_if_active_char_p:N" TeX-arg-macro)
     '("token_if_active_char:NT" TeX-arg-macro "true")
     '("token_if_active_char:NF" TeX-arg-macro "false")
     '("token_if_active_char:NTF" TeX-arg-macro "true" "false")
     '("token_if_eq_meaning_p:NN" TeX-arg-macro TeX-arg-macro)
     '("token_if_eq_meaning:NNT" TeX-arg-macro TeX-arg-macro "true")
     '("token_if_eq_meaning:NNF" TeX-arg-macro TeX-arg-macro "false")
     '("token_if_eq_meaning:NNTF" TeX-arg-macro TeX-arg-macro "true" "false")
     '("token_if_eq_catcode_p:NN" TeX-arg-macro TeX-arg-macro)
     '("token_if_eq_catcode:NNT" TeX-arg-macro TeX-arg-macro "true")
     '("token_if_eq_catcode:NNF" TeX-arg-macro TeX-arg-macro "false")
     '("token_if_eq_catcode:NNTF" TeX-arg-macro TeX-arg-macro "true" "false")
     '("token_if_eq_charcode_p:NN" TeX-arg-macro TeX-arg-macro)
     '("token_if_eq_charcode:NNT" TeX-arg-macro TeX-arg-macro "arg3")
     '("token_if_eq_charcode:NNF" TeX-arg-macro TeX-arg-macro "arg3")
     '("token_if_eq_charcode:NNTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("token_if_macro_p:N" TeX-arg-macro)
     '("token_if_macro:NT" TeX-arg-macro "true")
     '("token_if_macro:NF" TeX-arg-macro "false")
     '("token_if_macro:NTF" TeX-arg-macro "true" "false")
     '("token_if_cs_p:N" TeX-arg-macro)
     '("token_if_cs:NT" TeX-arg-macro "true")
     '("token_if_cs:NF" TeX-arg-macro "false")
     '("token_if_cs:NTF" TeX-arg-macro "true" "false")
     '("token_if_expandable_p:N" TeX-arg-macro)
     '("token_if_expandable:NT" TeX-arg-macro "true")
     '("token_if_expandable:NF" TeX-arg-macro "false")
     '("token_if_expandable:NTF" TeX-arg-macro "true" "false")
     '("token_if_long_macro_p:N" TeX-arg-macro)
     '("token_if_long_macro:NT" TeX-arg-macro "true")
     '("token_if_long_macro:NF" TeX-arg-macro "false")
     '("token_if_long_macro:NTF" TeX-arg-macro "true" "false")
     '("token_if_protected_macro_p:N" TeX-arg-macro)
     '("token_if_protected_macro:NT" TeX-arg-macro "arg2")
     '("token_if_protected_macro:NF" TeX-arg-macro "arg2")
     '("token_if_protected_macro:NTF" TeX-arg-macro "arg2" "arg3")
     '("token_if_protected_long_macro_p:N" TeX-arg-macro)
     '("token_if_protected_long_macro:NT" TeX-arg-macro "true")
     '("token_if_protected_long_macro:NF" TeX-arg-macro "false")
     '("token_if_protected_long_macro:NTF" TeX-arg-macro "true" "false")
     '("token_if_chardef_p:N" TeX-arg-macro)
     '("token_if_chardef:NT" TeX-arg-macro "true")
     '("token_if_chardef:NF" TeX-arg-macro "false")
     '("token_if_chardef:NTF" TeX-arg-macro "true" "false")
     '("token_if_mathchardef_p:N" TeX-arg-macro)
     '("token_if_mathchardef:NT" TeX-arg-macro "true")
     '("token_if_mathchardef:NF" TeX-arg-macro "false")
     '("token_if_mathchardef:NTF" TeX-arg-macro "true" "false")
     '("token_if_int_register_p:N" TeX-arg-macro)
     '("token_if_int_register:NT" TeX-arg-macro "true")
     '("token_if_int_register:NF" TeX-arg-macro "false")
     '("token_if_int_register:NTF" TeX-arg-macro "true" "false")
     '("token_if_dim_register_p:N" TeX-arg-macro)
     '("token_if_dim_register:NT" TeX-arg-macro "true")
     '("token_if_dim_register:NF" TeX-arg-macro "false")
     '("token_if_dim_register:NTF" TeX-arg-macro "true" "false")
     '("token_if_skip_register_p:N" TeX-arg-macro)
     '("token_if_skip_register:NT" TeX-arg-macro "true")
     '("token_if_skip_register:NF" TeX-arg-macro "false")
     '("token_if_skip_register:NTF" TeX-arg-macro "true" "false")
     '("token_if_toks_register_p:N" TeX-arg-macro)
     '("token_if_toks_register:NT" TeX-arg-macro "true")
     '("token_if_toks_register:NF" TeX-arg-macro "false")
     '("token_if_toks_register:NTF" TeX-arg-macro "true" "false")
     '("token_get_prefix_spec:N" TeX-arg-macro)
     '("token_get_arg_spec:N" TeX-arg-macro)
     '("token_get_replacement_spec:N" TeX-arg-macro)
     '("token_if_primitive_p:N" TeX-arg-macro)
     '("token_if_primitive:NT" TeX-arg-macro "true")
     '("token_if_primitive:NF" TeX-arg-macro "false")
     '("token_if_primitive:NTF" TeX-arg-macro "true" "false")
     '("peek_after:NN" TeX-arg-macro TeX-arg-macro)
     '("peek_gafter:NN" TeX-arg-macro TeX-arg-macro)
     '("peek_meaning:NT" TeX-arg-macro "true")
     '("peek_meaning:NF" TeX-arg-macro "false")
     '("peek_meaning:NTF" TeX-arg-macro "true" "false")
     '("peek_meaning_ignore_spaces:NT" TeX-arg-macro "arg2")
     '("peek_meaning_ignore_spaces:NF" TeX-arg-macro "arg2")
     '("peek_meaning_ignore_spaces:NTF" TeX-arg-macro "arg2" "arg3")
     '("peek_meaning_remove:NT" TeX-arg-macro "arg2")
     '("peek_meaning_remove:NF" TeX-arg-macro "arg2")
     '("peek_meaning_remove:NTF" TeX-arg-macro "arg2" "arg3")
     '("peek_meaning_remove_ignore_spaces:NT" TeX-arg-macro "arg2")
     '("peek_meaning_remove_ignore_spaces:NF" TeX-arg-macro "arg2")
     '("peek_meaning_remove_ignore_spaces:NTF" TeX-arg-macro "arg2" "arg3")
     '("peek_charcode:NT" TeX-arg-macro "true")
     '("peek_charcode:NF" TeX-arg-macro "false")
     '("peek_charcode:NTF" TeX-arg-macro "true" "false")
     '("peek_charcode_ignore_spaces:NT" TeX-arg-macro "arg2")
     '("peek_charcode_ignore_spaces:NF" TeX-arg-macro "arg2")
     '("peek_charcode_ignore_spaces:NTF" TeX-arg-macro "arg2" "arg3")
     '("peek_charcode_remove:NT" TeX-arg-macro "arg2")
     '("peek_charcode_remove:NF" TeX-arg-macro "arg2")
     '("peek_charcode_remove:NTF" TeX-arg-macro "arg2" "arg3")
     '("peek_charcode_remove_ignore_spaces:NT" TeX-arg-macro "arg2")
     '("peek_charcode_remove_ignore_spaces:NF" TeX-arg-macro "arg2")
     '("peek_charcode_remove_ignore_spaces:NTF" TeX-arg-macro "arg2" "arg3")
     '("peek_catcode:NT" TeX-arg-macro "true")
     '("peek_catcode:NF" TeX-arg-macro "false")
     '("peek_catcode:NTF" TeX-arg-macro "true" "false")
     '("peek_catcode_ignore_spaces:NT" TeX-arg-macro "arg2")
     '("peek_catcode_ignore_spaces:NF" TeX-arg-macro "arg2")
     '("peek_catcode_ignore_spaces:NTF" TeX-arg-macro "arg2" "arg3")
     '("peek_catcode_remove:NT" TeX-arg-macro "arg2")
     '("peek_catcode_remove:NF" TeX-arg-macro "arg2")
     '("peek_catcode_remove:NTF" TeX-arg-macro "arg2" "arg3")
     '("peek_catcode_remove_ignore_spaces:NT" TeX-arg-macro "arg2")
     '("peek_catcode_remove_ignore_spaces:NF" TeX-arg-macro "arg2")
     '("peek_catcode_remove_ignore_spaces:NTF" TeX-arg-macro "arg2" "arg3")
     '("peek_token_generic:NNT" TeX-arg-macro TeX-arg-macro "true")
     '("peek_token_generic:NNF" TeX-arg-macro TeX-arg-macro "false")
     '("peek_token_generic:NNTF" TeX-arg-macro TeX-arg-macro "true" "false")
     '("peek_token_remove_generic:NNT" TeX-arg-macro TeX-arg-macro "arg3")
     '("peek_token_remove_generic:NNF" TeX-arg-macro TeX-arg-macro "arg3")
     '("peek_token_remove_generic:NNTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     "peek_execute_branches_meaning:"
     "peek_execute_branches_charcode:"
     "peek_execute_branches_catcode:"
     "c_group_begin_token"
     "c_group_end_token"
     "c_math_shift_token"
     "c_alignment_tab_token"
     "c_parameter_token"
     "c_math_superscript_token"
     "c_math_subscript_token"
     "c_space_token"
     "c_letter_token"
     "c_other_char_token"
     "c_active_char_token"
     "l_peek_token"
     "g_peek_token"
     "l_peek_search_token"
     "l_peek_true_tl"
     "l_peek_false_tl"
     "l_peek_search_tl"
     "l_peek_true_aux_tl"
     "c_peek_true_remove_next_tl"
     '("clist_new:N" TeX-arg-macro)
     '("clist_new:c" "arg1")
     '("clist_clear:N" TeX-arg-macro)
     '("clist_clear:c" "arg1")
     '("clist_gclear:N" TeX-arg-macro)
     '("clist_gclear:c" "arg1")
     '("clist_clear_new:N" TeX-arg-macro)
     '("clist_clear_new:c" "arg1")
     '("clist_gclear_new:N" TeX-arg-macro)
     '("clist_gclear_new:c" "arg1")
     '("clist_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_set_eq:cN" "arg1" TeX-arg-macro)
     '("clist_set_eq:Nc" TeX-arg-macro "arg2")
     '("clist_set_eq:cc" "arg1" "arg2")
     '("clist_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_gset_eq:cN" "arg1" TeX-arg-macro)
     '("clist_gset_eq:Nc" TeX-arg-macro "arg2")
     '("clist_gset_eq:cc" "arg1" "arg2")
     '("clist_put_left:Nn" TeX-arg-macro TeX-arg-macro)
     '("clist_put_left:NV" TeX-arg-macro TeX-arg-macro)
     '("clist_put_left:No" TeX-arg-macro TeX-arg-macro)
     '("clist_put_left:Nx" TeX-arg-macro "arg2")
     '("clist_put_left:cn" "arg1" "arg2")
     '("clist_put_left:co" "arg1" TeX-arg-macro)
     '("clist_put_left:cV" "arg1" TeX-arg-macro)
     '("clist_put_right:Nn" TeX-arg-macro TeX-arg-macro)
     '("clist_put_right:No" TeX-arg-macro TeX-arg-macro)
     '("clist_put_right:NV" TeX-arg-macro TeX-arg-macro)
     '("clist_put_right:Nx" TeX-arg-macro "arg2")
     '("clist_put_right:cn" "arg1" "arg2")
     '("clist_put_right:co" "arg1" TeX-arg-macro)
     '("clist_put_right:cV" "arg1" TeX-arg-macro)
     '("clist_gput_left:Nn" TeX-arg-macro TeX-arg-macro)
     '("clist_gput_left:NV" TeX-arg-macro TeX-arg-macro)
     '("clist_gput_left:No" TeX-arg-macro TeX-arg-macro)
     '("clist_gput_left:Nx" TeX-arg-macro "arg2")
     '("clist_gput_left:cn" "arg1" "arg2")
     '("clist_gput_left:cV" "arg1" TeX-arg-macro)
     '("clist_gput_left:co" "arg1" TeX-arg-macro)
     '("clist_gput_right:Nn" TeX-arg-macro TeX-arg-macro)
     '("clist_gput_right:NV" TeX-arg-macro TeX-arg-macro)
     '("clist_gput_right:No" TeX-arg-macro TeX-arg-macro)
     '("clist_gput_right:Nx" TeX-arg-macro "arg2")
     '("clist_gput_right:cn" "arg1" "arg2")
     '("clist_gput_right:cV" "arg1" TeX-arg-macro)
     '("clist_gput_right:co" "arg1" TeX-arg-macro)
     '("clist_use:N" TeX-arg-macro)
     '("clist_use:c" "arg1")
     '("clist_show:N" TeX-arg-macro)
     '("clist_show:c" "arg1")
     '("clist_display:N" TeX-arg-macro)
     '("clist_display:c" "arg1")
     '("clist_get:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_get:cN" "arg1" TeX-arg-macro)
     '("clist_map_function:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_map_function:cN" "arg1" TeX-arg-macro)
     '("clist_map_function:nN" "arg1" TeX-arg-macro)
     '("clist_map_inline:Nn" TeX-arg-macro "inline function")
     '("clist_map_inline:cn" "arg1" "arg2")
     '("clist_map_inline:nn" "arg1" "arg2")
     '("clist_map_variable:NNn" TeX-arg-macro TeX-arg-macro "action")
     '("clist_map_variable:cNn" "arg1" TeX-arg-macro "arg3")
     '("clist_map_variable:nNn" "arg1" TeX-arg-macro "arg3")
     "clist_map_break:"
     '("clist_if_empty_p:N" TeX-arg-macro)
     '("clist_if_empty_p:c" "arg1")
     '("clist_if_empty:NT" TeX-arg-macro "true code")
     '("clist_if_empty:NF" TeX-arg-macro "false code")
     '("clist_if_empty:NTF" TeX-arg-macro "true code" "false code")
     '("clist_if_empty:cT" "arg1" "arg2")
     '("clist_if_empty:cF" "arg1" "arg2")
     '("clist_if_empty:cTF" "arg1" "arg2" "arg3")
     '("clist_if_eq_p:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_if_eq_p:cN" "arg1" TeX-arg-macro)
     '("clist_if_eq_p:Nc" TeX-arg-macro "arg2")
     '("clist_if_eq_p:cc" "arg1" "arg2")
     '("clist_if_eq:NNT" TeX-arg-macro TeX-arg-macro "true code")
     '("clist_if_eq:NNF" TeX-arg-macro TeX-arg-macro "false code")
     '("clist_if_eq:NNTF" TeX-arg-macro TeX-arg-macro "true code" "false code")
     '("clist_if_eq:cNT" "arg1" TeX-arg-macro "arg3")
     '("clist_if_eq:cNF" "arg1" TeX-arg-macro "arg3")
     '("clist_if_eq:cNTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("clist_if_eq:NcT" TeX-arg-macro "arg2" "arg3")
     '("clist_if_eq:NcF" TeX-arg-macro "arg2" "arg3")
     '("clist_if_eq:NcTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("clist_if_eq:ccT" "arg1" "arg2" "arg3")
     '("clist_if_eq:ccF" "arg1" "arg2" "arg3")
     '("clist_if_eq:ccTF" "arg1" "arg2" "arg3" "arg4")
     '("clist_if_in:NnT" TeX-arg-macro "item" "true code")
     '("clist_if_in:NnF" TeX-arg-macro "item" "false code")
     '("clist_if_in:NnTF" TeX-arg-macro "item" "true code" "false code")
     '("clist_if_in:NVT" TeX-arg-macro TeX-arg-macro "arg3")
     '("clist_if_in:NVF" TeX-arg-macro TeX-arg-macro "arg3")
     '("clist_if_in:NVTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("clist_if_in:NoT" TeX-arg-macro TeX-arg-macro "arg3")
     '("clist_if_in:NoF" TeX-arg-macro TeX-arg-macro "arg3")
     '("clist_if_in:NoTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("clist_if_in:cnT" "arg1" "arg2" "arg3")
     '("clist_if_in:cnF" "arg1" "arg2" "arg3")
     '("clist_if_in:cnTF" "arg1" "arg2" "arg3" "arg4")
     '("clist_if_in:cVT" "arg1" TeX-arg-macro "arg3")
     '("clist_if_in:cVF" "arg1" TeX-arg-macro "arg3")
     '("clist_if_in:cVTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("clist_if_in:coT" "arg1" TeX-arg-macro "arg3")
     '("clist_if_in:coF" "arg1" TeX-arg-macro "arg3")
     '("clist_if_in:coTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("clist_concat:NNN" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("clist_concat:ccc" "arg1" "arg2" "arg3")
     '("clist_gconcat:NNN" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("clist_gconcat:ccc" "arg1" "arg2" "arg3")
     '("clist_remove_duplicates:N" TeX-arg-macro)
     '("clist_gremove_duplicates:N" TeX-arg-macro)
     '("clist_remove_element:Nn" TeX-arg-macro "arg2")
     '("clist_gremove_element:Nn" TeX-arg-macro TeX-arg-macro)
     '("clist_push:Nn" TeX-arg-macro "token list")
     '("clist_push:NV" TeX-arg-macro TeX-arg-macro)
     '("clist_push:No" TeX-arg-macro TeX-arg-macro)
     '("clist_push:cn" "arg1" "arg2")
     '("clist_gpush:Nn" TeX-arg-macro "arg2")
     '("clist_gpush:NV" TeX-arg-macro TeX-arg-macro)
     '("clist_gpush:No" TeX-arg-macro TeX-arg-macro)
     '("clist_gpush:cn" "arg1" "arg2")
     '("clist_pop:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_pop:cN" "arg1" TeX-arg-macro)
     '("clist_gpop:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_gpop:cN" "arg1" TeX-arg-macro)
     '("clist_top:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_top:cN" "arg1" TeX-arg-macro)
     '("clist_if_empty_err:N" TeX-arg-macro)
     '("clist_pop_aux:nnNN" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("fp_new:N" TeX-arg-macro)
     '("fp_new:c" "arg1")
     '("fp_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("fp_set_eq:cN" "arg1" TeX-arg-macro)
     '("fp_set_eq:Nc" TeX-arg-macro "arg2")
     '("fp_set_eq:cc" "arg1" "arg2")
     '("fp_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("fp_gset_eq:cN" "arg1" TeX-arg-macro)
     '("fp_gset_eq:Nc" TeX-arg-macro "arg2")
     '("fp_gset_eq:cc" "arg1" "arg2")
     '("fp_zero:N" TeX-arg-macro)
     '("fp_zero:c" "arg1")
     '("fp_gzero:N" TeX-arg-macro)
     '("fp_gzero:c" "arg1")
     '("fp_set:Nn" TeX-arg-macro "arg2")
     '("fp_set:cn" "arg1" "arg2")
     '("fp_gset:Nn" TeX-arg-macro "arg2")
     '("fp_gset:cn" "arg1" "arg2")
     '("fp_set_from_dim:Nn" TeX-arg-macro "arg2")
     '("fp_set_from_dim:cn" "arg1" "arg2")
     '("fp_gset_from_dim:Nn" TeX-arg-macro "arg2")
     '("fp_gset_from_dim:cn" "arg1" "arg2")
     '("fp_use:N" TeX-arg-macro)
     '("fp_use:c" "arg1")
     '("fp_show:N" TeX-arg-macro)
     '("fp_show:c" "arg1")
     '("fp_to_int:N" TeX-arg-macro)
     '("fp_to_int:c" "arg1")
     '("fp_to_tl:N" TeX-arg-macro)
     '("fp_to_tl:c" "arg1")
     '("fp_round_figures:Nn" TeX-arg-macro "arg2")
     '("fp_round_figures:cn" "arg1" "arg2")
     '("fp_ground_figures:Nn" TeX-arg-macro "arg2")
     '("fp_ground_figures:cn" "arg1" "arg2")
     '("fp_round_places:Nn" TeX-arg-macro "arg2")
     '("fp_round_places:cn" "arg1" "arg2")
     '("fp_ground_places:Nn" TeX-arg-macro "arg2")
     '("fp_ground_places:cn" "arg1" "arg2")
     '("fp_abs:N" TeX-arg-macro)
     '("fp_abs:c" "arg1")
     '("fp_gabs:N" TeX-arg-macro)
     '("fp_gabs:c" "arg1")
     '("fp_neg:N" TeX-arg-macro)
     '("fp_neg:c" "arg1")
     '("fp_gneg:N" TeX-arg-macro)
     '("fp_gneg:c" "arg1")
     '("fp_add:Nn" TeX-arg-macro "arg2")
     '("fp_add:cn" "arg1" "arg2")
     '("fp_gadd:Nn" TeX-arg-macro "arg2")
     '("fp_gadd:cn" "arg1" "arg2")
     '("fp_sub:Nn" TeX-arg-macro "arg2")
     '("fp_sub:cn" "arg1" "arg2")
     '("fp_gsub:Nn" TeX-arg-macro "arg2")
     '("fp_gsub:cn" "arg1" "arg2")
     '("fp_mul:Nn" TeX-arg-macro "arg2")
     '("fp_mul:cn" "arg1" "arg2")
     '("fp_gmul:Nn" TeX-arg-macro "arg2")
     '("fp_gmul:cn" "arg1" "arg2")
     '("fp_div:Nn" TeX-arg-macro "arg2")
     '("fp_div:cn" "arg1" "arg2")
     '("fp_gdiv:Nn" TeX-arg-macro "arg2")
     '("fp_gdiv:cn" "arg1" "arg2")
     '("fp_sin:Nn" TeX-arg-macro "arg2")
     '("fp_sin:cn" "arg1" "arg2")
     '("fp_gsin:Nn" TeX-arg-macro "arg2")
     '("fp_gsin:cn" "arg1" "arg2")
     '("fp_cos:Nn" TeX-arg-macro "arg2")
     '("fp_cos:cn" "arg1" "arg2")
     '("fp_gcos:Nn" TeX-arg-macro "arg2")
     '("fp_gcos:cn" "arg1" "arg2")
     '("fp_tan:Nn" TeX-arg-macro "arg2")
     '("fp_tan:cn" "arg1" "arg2")
     '("fp_gtan:Nn" TeX-arg-macro "arg2")
     '("fp_gtan:cn" "arg1" "arg2")
     "c_infinity_fp"
     "c_undefined_fp"
     "c_zero_fp"
     '("seq_mapthread_function:NNN" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("seq_get_length:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_set_from_seq:NN" TeX-arg-macro TeX-arg-macro)
     '("clist_gset_from_seq:NN" TeX-arg-macro TeX-arg-macro)
     '("KV_parse_no_space_removal_no_sanitize:n" "keyval list")
     '("KV_parse_space_removal_no_sanitize:n" "keyval list")
     '("KV_parse_space_removal_sanitize:n" "keyval list")
     '("KV_sanitize_outerlevel_active_equals:N" TeX-arg-macro)
     '("KV_sanitize_outerlevel_active_commas:N" TeX-arg-macro)
     "KV_split_key_value_current:w"
     "KV_split_key_value_space_removal:w"
     "KV_split_key_value_space_removal_detect_error:wTF"
     "KV_split_key_value_no_space_removal:w"
     "l_KV_remove_one_level_of_braces_bool"
     "c_KV_single_equal_sign_tl"
     "l_KV_tmpa_tl"
     "l_KV_tmpb_tl"
     "l_KV_parse_tl"
     "l_KV_currkey_tl"
     "l_KV_currval_tl"
     '("calc_int_set:Nn" TeX-arg-macro "calc expression")
     '("calc_int_gset:Nn" TeX-arg-macro "arg2")
     '("calc_int_add:Nn" TeX-arg-macro "arg2")
     '("calc_int_gadd:Nn" TeX-arg-macro "arg2")
     '("calc_int_sub:Nn" TeX-arg-macro "arg2")
     '("calc_int_gsub:Nn" TeX-arg-macro "arg2")
     '("calc_dim_set:Nn" TeX-arg-macro "calc expression")
     '("calc_dim_gset:Nn" TeX-arg-macro "arg2")
     '("calc_dim_add:Nn" TeX-arg-macro "arg2")
     '("calc_dim_gadd:Nn" TeX-arg-macro "arg2")
     '("calc_dim_sub:Nn" TeX-arg-macro "arg2")
     '("calc_dim_gsub:Nn" TeX-arg-macro "arg2")
     '("calc_skip_set:Nn" TeX-arg-macro "calc expression")
     '("calc_skip_gset:Nn" TeX-arg-macro "arg2")
     '("calc_skip_add:Nn" TeX-arg-macro "arg2")
     '("calc_skip_gadd:Nn" TeX-arg-macro "arg2")
     '("calc_skip_sub:Nn" TeX-arg-macro "arg2")
     '("calc_skip_gsub:Nn" TeX-arg-macro "arg2")
     '("calc_muskip_set:Nn" TeX-arg-macro "calc expression")
     '("calc_muskip_gset:Nn" TeX-arg-macro "arg2")
     '("calc_muskip_add:Nn" TeX-arg-macro "arg2")
     '("calc_muskip_gadd:Nn" TeX-arg-macro "arg2")
     '("calc_muskip_sub:Nn" TeX-arg-macro "arg2")
     '("calc_muskip_gsub:Nn" TeX-arg-macro "arg2")
     '("cs_generate_internal_variant:n" "args")
     '("exp_args:No" TeX-arg-macro TeX-arg-macro)
     '("exp_args:Nc" TeX-arg-macro "arg2")
     '("exp_args:cc" "arg1" "arg2")
     '("exp_args:NV" TeX-arg-macro TeX-arg-macro)
     '("exp_args:Nv" TeX-arg-macro "arg2")
     '("exp_args:Nx" TeX-arg-macro "arg2")
     '("exp_args:Nf" TeX-arg-macro "arg2")
     '("exp_args:NNx" TeX-arg-macro TeX-arg-macro "arg3")
     '("exp_args:Nnx" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:Ncx" TeX-arg-macro "arg2" "arg3")
     '("exp_args:Nox" TeX-arg-macro TeX-arg-macro "arg3")
     '("exp_args:Nxo" TeX-arg-macro "arg2" TeX-arg-macro)
     '("exp_args:Nxx" TeX-arg-macro "arg2" "arg3")
     '("exp_args:NNo" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:NNc" TeX-arg-macro TeX-arg-macro "arg3")
     '("exp_args:NNv" TeX-arg-macro TeX-arg-macro "arg3")
     '("exp_args:NNV" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:NNf" TeX-arg-macro TeX-arg-macro "arg3")
     '("exp_args:Nno" TeX-arg-macro "arg2" TeX-arg-macro)
     '("exp_args:NnV" TeX-arg-macro "arg2" TeX-arg-macro)
     '("exp_args:Nnf" TeX-arg-macro "arg2" "arg3")
     '("exp_args:Noo" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:Noc" TeX-arg-macro TeX-arg-macro "arg3")
     '("exp_args:Nco" TeX-arg-macro "arg2" TeX-arg-macro)
     '("exp_args:Ncf" TeX-arg-macro "arg2" "arg3")
     '("exp_args:Ncc" TeX-arg-macro "arg2" "arg3")
     '("exp_args:Nff" TeX-arg-macro "arg2" "arg3")
     '("exp_args:Nfo" TeX-arg-macro "arg2" TeX-arg-macro)
     '("exp_args:NVV" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:NNnx" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("exp_args:NNox" TeX-arg-macro TeX-arg-macro TeX-arg-macro "arg4")
     '("exp_args:Nnnx" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:Nnox" TeX-arg-macro "arg2" TeX-arg-macro "arg4")
     '("exp_args:Noox" TeX-arg-macro TeX-arg-macro TeX-arg-macro "arg4")
     '("exp_args:Ncnx" TeX-arg-macro "arg2" "arg3" "arg4")
     '("exp_args:Nccx" TeX-arg-macro "arg2" "arg3" "arg4")
     '("exp_args:NNNo" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:NNNV" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:NNoo" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:NNno" TeX-arg-macro TeX-arg-macro "arg3" TeX-arg-macro)
     '("exp_args:Nnno" TeX-arg-macro "arg2" "arg3" TeX-arg-macro)
     '("exp_args:Nnnc" TeX-arg-macro "arg2" "arg3" "arg4")
     '("exp_args:Nooo" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_args:Nccc" TeX-arg-macro "arg2" "arg3" "arg4")
     '("exp_args:NcNc" TeX-arg-macro "arg2" TeX-arg-macro "arg4")
     '("exp_args:NcNo" TeX-arg-macro "arg2" TeX-arg-macro TeX-arg-macro)
     '("exp_args:Ncco" TeX-arg-macro "arg2" "arg3" TeX-arg-macro)
     '("exp_not:o" "token list")
     '("exp_not:f" "arg1")
     "exp_stop_f:"
     '("exp_last_unbraced:Nf" TeX-arg-macro "arg2")
     '("exp_last_unbraced:NV" TeX-arg-macro TeX-arg-macro)
     '("exp_last_unbraced:No" TeX-arg-macro TeX-arg-macro)
     '("exp_last_unbraced:Nv" TeX-arg-macro "arg2")
     '("exp_last_unbraced:NcV" TeX-arg-macro "arg2" TeX-arg-macro)
     '("exp_last_unbraced:NNV" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_last_unbraced:NNo" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_last_unbraced:NNNV" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_last_unbraced:NNNo" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("exp_after:wN" TeX-arg-macro TeX-arg-macro)
     '("exp_eval_register:N" TeX-arg-macro)
     '("exp_eval_register:c" "arg1")
     '("exp_eval_error_msg:w" TeX-arg-macro)
     "::n"
     "::N"
     "::c"
     "::o"
     "::f"
     "::x"
     "::v"
     "::V"
     ":::"
     "l_exp_tl"
     '("cs_gen_sym:N" TeX-arg-macro)
     '("cs_ggen_sym:N" TeX-arg-macro)
     '("cs_record_name:N" TeX-arg-macro)
     '("cs_record_name:c" "arg1")
     '("cs_record_meaning:N" TeX-arg-macro)
     '("register_record_name:N" TeX-arg-macro)
     '("cs_load_dump:n" "file name")
     "dumpLaTeXstate"
     "g_gen_sym_num"
     "g_ggen_sym_num"
     "g_cs_dump_seq"
     "g_cs_dump_stream"
     "g_cs_dump_name_tl"
     "g_cs_trace_seq"
     "g_register_trace_seq"
     '("toks_new:N" TeX-arg-macro)
     '("toks_new:c" "arg1")
     '("toks_use:N" TeX-arg-macro)
     '("toks_use:c" "arg1")
     '("toks_set:Nn" TeX-arg-macro "token list")
     '("toks_set:NV" TeX-arg-macro TeX-arg-macro)
     '("toks_set:Nv" TeX-arg-macro "arg2")
     '("toks_set:No" TeX-arg-macro TeX-arg-macro)
     '("toks_set:Nx" TeX-arg-macro "arg2")
     '("toks_set:Nf" TeX-arg-macro "arg2")
     '("toks_set:cn" "arg1" "arg2")
     '("toks_set:co" "arg1" TeX-arg-macro)
     '("toks_set:cV" "arg1" TeX-arg-macro)
     '("toks_set:cv" "arg1" "arg2")
     '("toks_set:cx" "arg1" "arg2")
     '("toks_set:cf" "arg1" "arg2")
     '("toks_gset:Nn" TeX-arg-macro "token list")
     '("toks_gset:NV" TeX-arg-macro TeX-arg-macro)
     '("toks_gset:No" TeX-arg-macro TeX-arg-macro)
     '("toks_gset:Nx" TeX-arg-macro "arg2")
     '("toks_gset:cn" "arg1" "arg2")
     '("toks_gset:cV" "arg1" TeX-arg-macro)
     '("toks_gset:co" "arg1" TeX-arg-macro)
     '("toks_gset:cx" "arg1" "arg2")
     '("toks_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("toks_set_eq:cN" "arg1" TeX-arg-macro)
     '("toks_set_eq:Nc" TeX-arg-macro "arg2")
     '("toks_set_eq:cc" "arg1" "arg2")
     '("toks_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("toks_gset_eq:cN" "arg1" TeX-arg-macro)
     '("toks_gset_eq:Nc" TeX-arg-macro "arg2")
     '("toks_gset_eq:cc" "arg1" "arg2")
     '("toks_clear:N" TeX-arg-macro)
     '("toks_clear:c" "arg1")
     '("toks_gclear:N" TeX-arg-macro)
     '("toks_gclear:c" "arg1")
     '("toks_use_clear:N" TeX-arg-macro)
     '("toks_use_clear:c" "arg1")
     '("toks_use_gclear:N" TeX-arg-macro)
     '("toks_use_gclear:c" "arg1")
     '("toks_show:N" TeX-arg-macro)
     '("toks_show:c" "arg1")
     '("toks_put_left:Nn" TeX-arg-macro "token list")
     '("toks_put_left:NV" TeX-arg-macro TeX-arg-macro)
     '("toks_put_left:No" TeX-arg-macro TeX-arg-macro)
     '("toks_put_left:Nx" TeX-arg-macro "arg2")
     '("toks_put_left:cn" "arg1" "arg2")
     '("toks_put_left:cV" "arg1" TeX-arg-macro)
     '("toks_put_left:co" "arg1" TeX-arg-macro)
     '("toks_gput_left:Nn" TeX-arg-macro "token list")
     '("toks_gput_left:NV" TeX-arg-macro TeX-arg-macro)
     '("toks_gput_left:No" TeX-arg-macro TeX-arg-macro)
     '("toks_gput_left:Nx" TeX-arg-macro "arg2")
     '("toks_gput_left:cn" "arg1" "arg2")
     '("toks_gput_left:cV" "arg1" TeX-arg-macro)
     '("toks_gput_left:co" "arg1" TeX-arg-macro)
     '("toks_put_right:Nn" TeX-arg-macro "token list")
     '("toks_put_right:NV" TeX-arg-macro TeX-arg-macro)
     '("toks_put_right:No" TeX-arg-macro TeX-arg-macro)
     '("toks_put_right:Nx" TeX-arg-macro "arg2")
     '("toks_put_right:cV" "arg1" TeX-arg-macro)
     '("toks_put_right:cn" "arg1" "arg2")
     '("toks_put_right:co" "arg1" TeX-arg-macro)
     '("toks_put_right:Nf" TeX-arg-macro "token list")
     '("toks_gput_right:Nn" TeX-arg-macro "token list")
     '("toks_gput_right:NV" TeX-arg-macro TeX-arg-macro)
     '("toks_gput_right:No" TeX-arg-macro TeX-arg-macro)
     '("toks_gput_right:Nx" TeX-arg-macro "arg2")
     '("toks_gput_right:cn" "arg1" "arg2")
     '("toks_gput_right:cV" "arg1" TeX-arg-macro)
     '("toks_gput_right:co" "arg1" TeX-arg-macro)
     '("toks_if_empty_p:N" TeX-arg-macro)
     '("toks_if_empty:NT" TeX-arg-macro "true code")
     '("toks_if_empty:NF" TeX-arg-macro "false code")
     '("toks_if_empty:NTF" TeX-arg-macro "true code" "false code")
     '("toks_if_empty_p:c" "arg1")
     '("toks_if_empty:cT" "arg1" "arg2")
     '("toks_if_empty:cF" "arg1" "arg2")
     '("toks_if_empty:cTF" "arg1" "arg2" "arg3")
     '("toks_if_eq:NNT" TeX-arg-macro TeX-arg-macro "true code")
     '("toks_if_eq:NNF" TeX-arg-macro TeX-arg-macro "false code")
     '("toks_if_eq:NNTF" TeX-arg-macro TeX-arg-macro "true code" "false code")
     '("toks_if_eq:NcT" TeX-arg-macro "arg2" "arg3")
     '("toks_if_eq:NcF" TeX-arg-macro "arg2" "arg3")
     '("toks_if_eq:NcTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("toks_if_eq:cNT" "arg1" TeX-arg-macro "arg3")
     '("toks_if_eq:cNF" "arg1" TeX-arg-macro "arg3")
     '("toks_if_eq:cNTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("toks_if_eq:ccT" "arg1" "arg2" "arg3")
     '("toks_if_eq:ccF" "arg1" "arg2" "arg3")
     '("toks_if_eq:ccTF" "arg1" "arg2" "arg3" "arg4")
     '("toks_if_eq_p:NN" TeX-arg-macro TeX-arg-macro)
     '("toks_if_eq_p:cN" "arg1" TeX-arg-macro)
     '("toks_if_eq_p:Nc" TeX-arg-macro "arg2")
     '("toks_if_eq_p:cc" "arg1" "arg2")
     "c_empty_toks"
     "l_tmpa_toks"
     "l_tmpb_toks"
     "l_tmpc_toks"
     "g_tmpa_toks"
     "g_tmpb_toks"
     "g_tmpc_toks"
     "l_tl_replace_toks"
     '("tl_new:N" TeX-arg-macro)
     '("tl_new:c" "arg1")
     '("tl_new:Nn" TeX-arg-macro "initial token list")
     '("tl_new:cn" "arg1" "arg2")
     '("tl_new:Nx" TeX-arg-macro "arg2")
     '("tl_const:Nn" "token list")
     '("tl_use:N" TeX-arg-macro)
     '("tl_use:c" "arg1")
     '("tl_set:Nn" TeX-arg-macro "\tlist")
     '("tl_set:Nc" TeX-arg-macro "arg2")
     '("tl_set:NV" TeX-arg-macro TeX-arg-macro)
     '("tl_set:No" TeX-arg-macro TeX-arg-macro)
     '("tl_set:Nv" TeX-arg-macro "arg2")
     '("tl_set:Nf" TeX-arg-macro "arg2")
     '("tl_set:Nx" TeX-arg-macro "arg2")
     '("tl_set:cn" "arg1" "arg2")
     '("tl_set:co" "arg1" TeX-arg-macro)
     '("tl_set:cV" "arg1" TeX-arg-macro)
     '("tl_set:cx" "arg1" "arg2")
     '("tl_gset:Nn" TeX-arg-macro "arg2")
     '("tl_gset:Nc" TeX-arg-macro "arg2")
     '("tl_gset:No" TeX-arg-macro TeX-arg-macro)
     '("tl_gset:NV" TeX-arg-macro TeX-arg-macro)
     '("tl_gset:Nv" TeX-arg-macro "arg2")
     '("tl_gset:Nx" TeX-arg-macro "arg2")
     '("tl_gset:cn" "arg1" "arg2")
     '("tl_gset:cx" "arg1" "arg2")
     '("tl_clear:N" TeX-arg-macro)
     '("tl_clear:c" "arg1")
     '("tl_gclear:N" TeX-arg-macro)
     '("tl_gclear:c" "arg1")
     '("tl_clear_new:N" TeX-arg-macro)
     '("tl_clear_new:c" "arg1")
     '("tl_gclear_new:N" TeX-arg-macro)
     '("tl_gclear_new:c" "arg1")
     '("tl_put_left:Nn" TeX-arg-macro "\tlist")
     '("tl_put_left:NV" TeX-arg-macro TeX-arg-macro)
     '("tl_put_left:No" TeX-arg-macro TeX-arg-macro)
     '("tl_put_left:Nx" TeX-arg-macro "arg2")
     '("tl_put_left:cn" "arg1" "arg2")
     '("tl_put_left:cV" "arg1" TeX-arg-macro)
     '("tl_put_left:co" "arg1" TeX-arg-macro)
     '("tl_put_right:Nn" TeX-arg-macro "\tlist")
     '("tl_put_right:NV" TeX-arg-macro TeX-arg-macro)
     '("tl_put_right:No" TeX-arg-macro TeX-arg-macro)
     '("tl_put_right:Nx" TeX-arg-macro "arg2")
     '("tl_put_right:cn" "arg1" "arg2")
     '("tl_put_right:cV" "arg1" TeX-arg-macro)
     '("tl_put_right:co" "arg1" TeX-arg-macro)
     '("tl_gput_left:Nn" TeX-arg-macro "\tlist")
     '("tl_gput_left:No" TeX-arg-macro TeX-arg-macro)
     '("tl_gput_left:NV" TeX-arg-macro TeX-arg-macro)
     '("tl_gput_left:Nx" TeX-arg-macro "arg2")
     '("tl_gput_left:cn" "arg1" "arg2")
     '("tl_gput_left:co" "arg1" TeX-arg-macro)
     '("tl_gput_left:cV" "arg1" TeX-arg-macro)
     '("tl_gput_right:Nn" TeX-arg-macro "\tlist")
     '("tl_gput_right:No" TeX-arg-macro TeX-arg-macro)
     '("tl_gput_right:NV" TeX-arg-macro TeX-arg-macro)
     '("tl_gput_right:Nx" TeX-arg-macro "arg2")
     '("tl_gput_right:cn" "arg1" "arg2")
     '("tl_gput_right:co" "arg1" TeX-arg-macro)
     '("tl_gput_right:cV" "arg1" TeX-arg-macro)
     '("tl_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("tl_set_eq:Nc" TeX-arg-macro "arg2")
     '("tl_set_eq:cN" "arg1" TeX-arg-macro)
     '("tl_set_eq:cc" "arg1" "arg2")
     '("tl_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("tl_gset_eq:Nc" TeX-arg-macro "arg2")
     '("tl_gset_eq:cN" "arg1" TeX-arg-macro)
     '("tl_gset_eq:cc" "arg1" "arg2")
     '("tl_to_str:N" TeX-arg-macro)
     '("tl_to_str:c" "arg1")
     '("tl_to_str:n" "\tlist")
     '("tl_rescan:nn" "catcode setup" "\tlist")
     '("tl_set_rescan:Nnn" TeX-arg-macro "catcode setup" "\tlist")
     '("tl_set_rescan:Nnx" TeX-arg-macro "arg2" "arg3")
     '("tl_gset_rescan:Nnn" TeX-arg-macro "arg2" "arg3")
     '("tl_gset_rescan:Nnx" TeX-arg-macro "arg2" "arg3")
     '("tl_if_empty_p:N" TeX-arg-macro)
     '("tl_if_empty_p:c" "arg1")
     '("tl_if_empty:NT" TeX-arg-macro "true code")
     '("tl_if_empty:NF" TeX-arg-macro "false code")
     '("tl_if_empty:NTF" TeX-arg-macro "true code" "false code")
     '("tl_if_empty:cT" "arg1" "arg2")
     '("tl_if_empty:cF" "arg1" "arg2")
     '("tl_if_empty:cTF" "arg1" "arg2" "arg3")
     '("tl_if_eq_p:NN" TeX-arg-macro TeX-arg-macro)
     '("tl_if_eq_p:cN" "arg1" TeX-arg-macro)
     '("tl_if_eq_p:Nc" TeX-arg-macro "arg2")
     '("tl_if_eq_p:cc" "arg1" "arg2")
     '("tl_if_eq:NNT" TeX-arg-macro TeX-arg-macro "true code")
     '("tl_if_eq:NNF" TeX-arg-macro TeX-arg-macro "false code")
     '("tl_if_eq:NNTF" TeX-arg-macro TeX-arg-macro "true code" "false code")
     '("tl_if_eq:cNT" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:cNF" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:cNTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("tl_if_eq:NcT" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:NcF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:NcTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("tl_if_eq:ccT" "arg1" "arg2" "arg3")
     '("tl_if_eq:ccF" "arg1" "arg2" "arg3")
     '("tl_if_eq:ccTF" "arg1" "arg2" "arg3" "arg4")
     '("tl_if_eq:nnT" "tlist1" "tlist2" "true code")
     '("tl_if_eq:nnF" "tlist1" "tlist2" "false code")
     '("tl_if_eq:nnTF" "tlist1" "tlist2" "true code" "false code")
     '("tl_if_eq:nVT" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:nVF" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:nVTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("tl_if_eq:noT" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:noF" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:noTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("tl_if_eq:VnT" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:VnF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:VnTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("tl_if_eq:onT" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:onF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:onTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("tl_if_eq:VVT" TeX-arg-macro TeX-arg-macro "arg3")
     '("tl_if_eq:VVF" TeX-arg-macro TeX-arg-macro "arg3")
     '("tl_if_eq:VVTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("tl_if_eq:ooT" TeX-arg-macro TeX-arg-macro "arg3")
     '("tl_if_eq:ooF" TeX-arg-macro TeX-arg-macro "arg3")
     '("tl_if_eq:ooTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("tl_if_eq:xxT" "arg1" "arg2" "arg3")
     '("tl_if_eq:xxF" "arg1" "arg2" "arg3")
     '("tl_if_eq:xxTF" "arg1" "arg2" "arg3" "arg4")
     '("tl_if_eq:xnT" "arg1" "arg2" "arg3")
     '("tl_if_eq:xnF" "arg1" "arg2" "arg3")
     '("tl_if_eq:xnTF" "arg1" "arg2" "arg3" "arg4")
     '("tl_if_eq:nxT" "arg1" "arg2" "arg3")
     '("tl_if_eq:nxF" "arg1" "arg2" "arg3")
     '("tl_if_eq:nxTF" "arg1" "arg2" "arg3" "arg4")
     '("tl_if_eq:xVT" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:xVF" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:xVTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("tl_if_eq:xoT" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:xoF" "arg1" TeX-arg-macro "arg3")
     '("tl_if_eq:xoTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("tl_if_eq:VxT" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:VxF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:VxTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("tl_if_eq:oxT" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:oxF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_eq:oxTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("tl_if_eq_p:nn" "tlist1" "tlist2")
     '("tl_if_eq_p:nV" "arg1" TeX-arg-macro)
     '("tl_if_eq_p:no" "arg1" TeX-arg-macro)
     '("tl_if_eq_p:Vn" TeX-arg-macro "arg2")
     '("tl_if_eq_p:on" TeX-arg-macro "arg2")
     '("tl_if_eq_p:VV" TeX-arg-macro TeX-arg-macro)
     '("tl_if_eq_p:oo" TeX-arg-macro TeX-arg-macro)
     '("tl_if_eq_p:xx" "arg1" "arg2")
     '("tl_if_eq_p:xn" "arg1" "arg2")
     '("tl_if_eq_p:nx" "arg1" "arg2")
     '("tl_if_eq_p:xV" "arg1" TeX-arg-macro)
     '("tl_if_eq_p:xo" "arg1" TeX-arg-macro)
     '("tl_if_eq_p:Vx" TeX-arg-macro "arg2")
     '("tl_if_eq_p:ox" TeX-arg-macro "arg2")
     '("tl_if_empty_p:n" "arg1")
     '("tl_if_empty_p:V" TeX-arg-macro)
     '("tl_if_empty_p:o" TeX-arg-macro)
     '("tl_if_empty:nT" "\tlist" "true code")
     '("tl_if_empty:nF" "\tlist" "false code")
     '("tl_if_empty:nTF" "\tlist" "true code" "false code")
     '("tl_if_empty:VT" TeX-arg-macro "arg2")
     '("tl_if_empty:VF" TeX-arg-macro "arg2")
     '("tl_if_empty:VTF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_empty:oT" TeX-arg-macro "arg2")
     '("tl_if_empty:oF" TeX-arg-macro "arg2")
     '("tl_if_empty:oTF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_blank_p:n" "arg1")
     '("tl_if_blank:nT" "\tlist" "true code")
     '("tl_if_blank:nF" "\tlist" "false code")
     '("tl_if_blank:nTF" "\tlist" "true code" "false code")
     '("tl_if_blank_p:V" TeX-arg-macro)
     '("tl_if_blank_p:o" TeX-arg-macro)
     '("tl_if_blank:VT" TeX-arg-macro "arg2")
     '("tl_if_blank:VF" TeX-arg-macro "arg2")
     '("tl_if_blank:VTF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_blank:oT" TeX-arg-macro "arg2")
     '("tl_if_blank:oF" TeX-arg-macro "arg2")
     '("tl_if_blank:oTF" TeX-arg-macro "arg2" "arg3")
     '("tl_to_lowercase:n" "\tlist")
     '("tl_to_uppercase:n" "arg1")
     "tl_map_break:"
     '("tl_if_in:NnT" TeX-arg-macro "item" "true code")
     '("tl_if_in:NnF" TeX-arg-macro "item" "false code")
     '("tl_if_in:NnTF" TeX-arg-macro "item" "true code" "false code")
     '("tl_if_in:cnT" "arg1" "arg2" "arg3")
     '("tl_if_in:cnF" "arg1" "arg2" "arg3")
     '("tl_if_in:cnTF" "arg1" "arg2" "arg3" "arg4")
     '("tl_if_in:nnT" "arg1" "arg2" "arg3")
     '("tl_if_in:nnF" "arg1" "arg2" "arg3")
     '("tl_if_in:nnTF" "arg1" "arg2" "arg3" "arg4")
     '("tl_if_in:VnT" TeX-arg-macro "arg2" "arg3")
     '("tl_if_in:VnF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_in:VnTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("tl_if_in:onT" TeX-arg-macro "arg2" "arg3")
     '("tl_if_in:onF" TeX-arg-macro "arg2" "arg3")
     '("tl_if_in:onTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("tl_replace_in:Nnn" TeX-arg-macro "item1" "item2")
     '("tl_replace_in:cnn" "arg1" "arg2" "arg3")
     '("tl_greplace_in:Nnn" TeX-arg-macro "arg2" "arg3")
     '("tl_greplace_in:cnn" "arg1" "arg2" "arg3")
     '("tl_replace_all_in:Nnn" TeX-arg-macro "item1" "item2")
     '("tl_replace_all_in:cnn" "arg1" "arg2" "arg3")
     '("tl_greplace_all_in:Nnn" TeX-arg-macro "arg2" "arg3")
     '("tl_greplace_all_in:cnn" "arg1" "arg2" "arg3")
     '("tl_remove_in:Nn" TeX-arg-macro "item")
     '("tl_remove_in:cn" "arg1" "arg2")
     '("tl_gremove_in:Nn" TeX-arg-macro "arg2")
     '("tl_gremove_in:cn" "arg1" "arg2")
     '("tl_remove_all_in:Nn" TeX-arg-macro "item")
     '("tl_remove_all_in:cn" "arg1" "arg2")
     '("tl_gremove_all_in:Nn" TeX-arg-macro "arg2")
     '("tl_gremove_all_in:cn" "arg1" "arg2")
     "c_job_name_tl"
     "c_empty_tl"
     "c_space_tl"
     "l_tmpa_tl"
     "l_tmpb_tl"
     "g_tmpa_tl"
     "g_tmpb_tl"
     "l_tl_replace_tl"
     "l_kernel_testa_tl"
     "l_kernel_testb_tl"
     "l_kernel_tmpa_tl"
     "l_kernel_tmpb_tl"
     "g_tl_inline_level_int"
     '("skip_new:N" TeX-arg-macro)
     '("skip_new:c" "arg1")
     '("skip_zero:N" TeX-arg-macro)
     '("skip_zero:c" "arg1")
     '("skip_gzero:N" TeX-arg-macro)
     '("skip_gzero:c" "arg1")
     '("skip_set:Nn" TeX-arg-macro "skip value")
     '("skip_set:cn" "arg1" "arg2")
     '("skip_gset:Nn" TeX-arg-macro "arg2")
     '("skip_gset:cn" "arg1" "arg2")
     '("skip_add:Nn" TeX-arg-macro "length")
     '("skip_add:cn" "arg1" "arg2")
     '("skip_gadd:Nn" TeX-arg-macro "arg2")
     '("skip_gadd:cn" "arg1" "arg2")
     '("skip_sub:Nn" TeX-arg-macro "arg2")
     '("skip_gsub:Nn" TeX-arg-macro "length")
     '("skip_use:N" TeX-arg-macro)
     '("skip_use:c" "arg1")
     '("skip_show:N" TeX-arg-macro)
     '("skip_show:c" "arg1")
     '("skip_if_infinite_glue_p:n" "arg1")
     '("skip_if_infinite_glue:nT" "skip" "true")
     '("skip_if_infinite_glue:nF" "skip" "false")
     '("skip_if_infinite_glue:nTF" "skip" "true" "false")
     '("skip_eval:n" "skip expr")
     '("dim_new:N" TeX-arg-macro)
     '("dim_new:c" "arg1")
     '("dim_zero:N" TeX-arg-macro)
     '("dim_zero:c" "arg1")
     '("dim_gzero:N" TeX-arg-macro)
     '("dim_gzero:c" "arg1")
     '("dim_set:Nn" TeX-arg-macro "dim value")
     '("dim_set:Nc" TeX-arg-macro "arg2")
     '("dim_set:cn" "arg1" "arg2")
     '("dim_gset:Nn" TeX-arg-macro "arg2")
     '("dim_gset:Nc" TeX-arg-macro "arg2")
     '("dim_gset:cn" "arg1" "arg2")
     '("dim_gset:cc" "arg1" "arg2")
     '("dim_add:Nn" TeX-arg-macro "length")
     '("dim_add:Nc" TeX-arg-macro "arg2")
     '("dim_add:cn" "arg1" "arg2")
     '("dim_gadd:Nn" TeX-arg-macro "arg2")
     '("dim_gadd:cn" "arg1" "arg2")
     '("dim_sub:Nn" TeX-arg-macro "arg2")
     '("dim_sub:Nc" TeX-arg-macro "arg2")
     '("dim_sub:cn" "arg1" "arg2")
     '("dim_gsub:Nn" TeX-arg-macro "length")
     '("dim_gsub:cn" "arg1" "arg2")
     '("dim_use:N" TeX-arg-macro)
     '("dim_use:c" "arg1")
     '("dim_show:N" TeX-arg-macro)
     '("dim_show:c" "arg1")
     '("dim_eval:n" "dim expr")
     '("if_dim:w" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("dim_while_do:nNnn" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("dim_until_do:nNnn" "arg1" TeX-arg-macro "arg3" "arg4")
     '("dim_do_while:nNnn" "arg1" TeX-arg-macro "arg3" "arg4")
     '("dim_do_until:nNnn" "arg1" TeX-arg-macro "arg3" "arg4")
     '("muskip_new:N" TeX-arg-macro)
     '("muskip_set:Nn" TeX-arg-macro "muskip value")
     '("muskip_gset:Nn" TeX-arg-macro "arg2")
     '("muskip_add:Nn" TeX-arg-macro "length")
     '("muskip_gadd:Nn" TeX-arg-macro "arg2")
     '("muskip_sub:Nn" TeX-arg-macro "arg2")
     '("muskip_gsub:Nn" TeX-arg-macro "length")
     '("muskip_use:N" TeX-arg-macro)
     '("muskip_show:N" TeX-arg-macro)
     "c_max_skip"
     "c_zero_skip"
     "l_tmpa_skip"
     "l_tmpb_skip"
     "l_tmpc_skip"
     "g_tmpa_skip"
     "g_tmpb_skip"
     "c_max_dim"
     "c_zero_dim"
     "l_tmpa_dim"
     "l_tmpb_dim"
     "l_tmpc_dim"
     "l_tmpd_dim"
     "g_tmpa_dim"
     "g_tmpb_dim"
     '("int_new:N" TeX-arg-macro)
     '("int_new:c" "arg1")
     '("int_incr:N" TeX-arg-macro)
     '("int_incr:c" "arg1")
     '("int_gincr:N" TeX-arg-macro)
     '("int_gincr:c" "arg1")
     '("int_decr:N" TeX-arg-macro)
     '("int_decr:c" "arg1")
     '("int_gdecr:N" TeX-arg-macro)
     '("int_gdecr:c" "arg1")
     '("int_set:Nn" TeX-arg-macro "integer expr")
     '("int_set:cn" "arg1" "arg2")
     '("int_gset:Nn" TeX-arg-macro "arg2")
     '("int_gset:cn" "arg1" "arg2")
     '("int_zero:N" TeX-arg-macro)
     '("int_zero:c" "arg1")
     '("int_gzero:N" TeX-arg-macro)
     '("int_gzero:c" "arg1")
     '("int_add:Nn" TeX-arg-macro "integer expr")
     '("int_add:cn" "arg1" "arg2")
     '("int_gadd:Nn" TeX-arg-macro "arg2")
     '("int_gadd:cn" "arg1" "arg2")
     '("int_sub:Nn" TeX-arg-macro "arg2")
     '("int_sub:cn" "arg1" "arg2")
     '("int_gsub:Nn" TeX-arg-macro "integer expr")
     '("int_gsub:cn" "arg1" "arg2")
     '("int_use:N" TeX-arg-macro)
     '("int_use:c" "arg1")
     '("int_show:N" TeX-arg-macro)
     '("int_show:c" "arg1")
     '("int_to_roman:w" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("int_to_number:w" TeX-arg-macro TeX-arg-macro)
     '("int_const:Nn" TeX-arg-macro "value")
     '("int_convert_from_base_ten:nn" "number" "base")
     '("int_convert_to_base_ten:nn" "number" "base")
     '("int_advance:w" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("int_convert_number_to_letter:n" "integer expression")
     '("int_get_sign_and_digits:n" "number")
     '("int_get_sign:n" "arg1")
     '("int_get_digits:n" "arg1")
     "c_minus_one"
     "c_zero"
     "c_one"
     "c_two"
     "c_three"
     "c_four"
     "c_five"
     "c_six"
     "c_seven"
     "c_eight"
     "c_nine"
     "c_ten"
     "c_eleven"
     "c_twelve"
     "c_thirteen"
     "c_fourteen"
     "c_fifteen"
     "c_sixteen"
     "c_thirty_two"
     "c_hundred_one"
     "c_twohundred_fifty_five"
     "c_twohundred_fifty_six"
     "c_thousand"
     "c_ten_thousand"
     "c_ten_thousand_one"
     "c_ten_thousand_two"
     "c_ten_thousand_three"
     "c_ten_thousand_four"
     "c_twenty_thousand"
     "c_max_int"
     "c_max_register_int"
     "l_tmpa_int"
     "l_tmpb_int"
     "l_tmpc_int"
     "g_tmpa_int"
     "g_tmpb_int"
     '("prop_new:N" TeX-arg-macro)
     '("prop_new:c" "arg1")
     '("prop_clear:N" TeX-arg-macro)
     '("prop_clear:c" "arg1")
     '("prop_gclear:N" TeX-arg-macro)
     '("prop_gclear:c" "arg1")
     '("prop_put:Nnn" TeX-arg-macro "\propkey" "token list")
     '("prop_put:NnV" TeX-arg-macro "arg2" TeX-arg-macro)
     '("prop_put:NVn" TeX-arg-macro TeX-arg-macro "arg3")
     '("prop_put:NVV" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("prop_put:cnn" "arg1" "arg2" "arg3")
     '("prop_gput:Nnn" TeX-arg-macro "arg2" "arg3")
     '("prop_gput:NVn" TeX-arg-macro TeX-arg-macro "arg3")
     '("prop_gput:Nno" TeX-arg-macro "arg2" TeX-arg-macro)
     '("prop_gput:NnV" TeX-arg-macro "arg2" TeX-arg-macro)
     '("prop_gput:Nnx" TeX-arg-macro "arg2" "arg3")
     '("prop_gput:cnn" "arg1" "arg2" "arg3")
     '("prop_gput:ccx" "arg1" "arg2" "arg3")
     '("prop_gput_if_new:Nnn" TeX-arg-macro "\propkey" "token list")
     '("prop_get:NnN" TeX-arg-macro "\propkey" TeX-arg-macro)
     '("prop_get:NVN" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("prop_get:cnN" "arg1" "arg2" TeX-arg-macro)
     '("prop_get:cVN" "arg1" TeX-arg-macro TeX-arg-macro)
     '("prop_gget:NnN" TeX-arg-macro "arg2" TeX-arg-macro)
     '("prop_gget:NVN" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("prop_gget:cnN" "arg1" "arg2" TeX-arg-macro)
     '("prop_gget:cVN" "arg1" TeX-arg-macro TeX-arg-macro)
     '("prop_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("prop_set_eq:cN" "arg1" TeX-arg-macro)
     '("prop_set_eq:Nc" TeX-arg-macro "arg2")
     '("prop_set_eq:cc" "arg1" "arg2")
     '("prop_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("prop_gset_eq:cN" "arg1" TeX-arg-macro)
     '("prop_gset_eq:Nc" TeX-arg-macro "arg2")
     '("prop_gset_eq:cc" "arg1" "arg2")
     '("prop_get_gdel:NnN" TeX-arg-macro "\propkey" TeX-arg-macro)
     '("prop_del:Nn" TeX-arg-macro "\propkey")
     '("prop_del:NV" TeX-arg-macro TeX-arg-macro)
     '("prop_gdel:Nn" TeX-arg-macro "arg2")
     '("prop_gdel:NV" TeX-arg-macro TeX-arg-macro)
     '("prop_map_function:NN" TeX-arg-macro TeX-arg-macro)
     '("prop_map_function:cN" "arg1" TeX-arg-macro)
     '("prop_map_function:Nc" TeX-arg-macro "arg2")
     '("prop_map_function:cc" "arg1" "arg2")
     '("prop_map_inline:Nn" TeX-arg-macro "inline function")
     '("prop_map_inline:cn" "arg1" "arg2")
     '("prop_show:N" TeX-arg-macro)
     '("prop_show:c" "arg1")
     '("prop_display:N" TeX-arg-macro)
     '("prop_display:c" "arg1")
     '("prop_if_empty_p:N" TeX-arg-macro "true code" "false code")
     '("prop_if_empty_p:c" "arg1")
     '("prop_if_empty:NT" TeX-arg-macro "true code")
     '("prop_if_empty:NF" TeX-arg-macro "false code")
     '("prop_if_empty:NTF" TeX-arg-macro "true code" "false code")
     '("prop_if_empty:cT" "arg1" "arg2")
     '("prop_if_empty:cF" "arg1" "arg2")
     '("prop_if_empty:cTF" "arg1" "arg2" "arg3")
     '("prop_if_eq_p:NN" TeX-arg-macro TeX-arg-macro)
     '("prop_if_eq_p:cN" "arg1" TeX-arg-macro)
     '("prop_if_eq_p:Nc" TeX-arg-macro "arg2")
     '("prop_if_eq_p:cc" "arg1" "arg2")
     '("prop_if_eq:NNT" TeX-arg-macro TeX-arg-macro "arg3")
     '("prop_if_eq:NNF" TeX-arg-macro TeX-arg-macro "false code")
     '("prop_if_eq:NNTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("prop_if_eq:cNT" "arg1" TeX-arg-macro "arg3")
     '("prop_if_eq:cNF" "arg1" TeX-arg-macro "arg3")
     '("prop_if_eq:cNTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("prop_if_eq:NcT" TeX-arg-macro "arg2" "arg3")
     '("prop_if_eq:NcF" TeX-arg-macro "arg2" "arg3")
     '("prop_if_eq:NcTF" TeX-arg-macro "arg2" "arg3" "arg4")
     '("prop_if_eq:ccT" "arg1" "arg2" "arg3")
     '("prop_if_eq:ccF" "arg1" "arg2" "arg3")
     '("prop_if_eq:ccTF" "arg1" "arg2" "arg3" "arg4")
     '("prop_if_in:NnT" TeX-arg-macro "\propkey" "true code")
     '("prop_if_in:NnF" TeX-arg-macro "\propkey" "false code")
     '("prop_if_in:NnTF" TeX-arg-macro "\propkey" "true code" "false code")
     '("prop_if_in:NVT" TeX-arg-macro TeX-arg-macro "arg3")
     '("prop_if_in:NVF" TeX-arg-macro TeX-arg-macro "arg3")
     '("prop_if_in:NVTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("prop_if_in:NoT" TeX-arg-macro TeX-arg-macro "arg3")
     '("prop_if_in:NoF" TeX-arg-macro TeX-arg-macro "arg3")
     '("prop_if_in:NoTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("prop_if_in:cnT" "arg1" "arg2" "arg3")
     '("prop_if_in:cnF" "arg1" "arg2" "arg3")
     '("prop_if_in:cnTF" "arg1" "arg2" "arg3" "arg4")
     '("prop_if_in:ccT" "arg1" "arg2" "arg3")
     '("prop_if_in:ccF" "arg1" "arg2" "arg3")
     '("prop_if_in:ccTF" "arg1" "arg2" "arg3" "arg4")
     '("prop_split_aux:Nnn" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("seq_new:N" TeX-arg-macro)
     '("seq_new:c" "arg1")
     '("seq_clear:N" TeX-arg-macro)
     '("seq_clear:c" "arg1")
     '("seq_gclear:N" TeX-arg-macro)
     '("seq_gclear:c" "arg1")
     '("seq_clear_new:N" TeX-arg-macro)
     '("seq_clear_new:c" "arg1")
     '("seq_gclear_new:N" TeX-arg-macro)
     '("seq_gclear_new:c" "arg1")
     '("seq_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("seq_set_eq:cN" "arg1" TeX-arg-macro)
     '("seq_set_eq:Nc" TeX-arg-macro "arg2")
     '("seq_set_eq:cc" "arg1" "arg2")
     '("seq_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("seq_gset_eq:cN" "arg1" TeX-arg-macro)
     '("seq_gset_eq:Nc" TeX-arg-macro "arg2")
     '("seq_gset_eq:cc" "arg1" "arg2")
     '("seq_put_left:Nn" TeX-arg-macro TeX-arg-macro)
     '("seq_put_left:NV" TeX-arg-macro TeX-arg-macro)
     '("seq_put_left:No" TeX-arg-macro TeX-arg-macro)
     '("seq_put_left:Nx" TeX-arg-macro "arg2")
     '("seq_put_left:cn" "arg1" "arg2")
     '("seq_put_left:cV" "arg1" TeX-arg-macro)
     '("seq_put_left:co" "arg1" TeX-arg-macro)
     '("seq_put_right:Nn" TeX-arg-macro TeX-arg-macro)
     '("seq_put_right:NV" TeX-arg-macro TeX-arg-macro)
     '("seq_put_right:No" TeX-arg-macro TeX-arg-macro)
     '("seq_put_right:Nx" TeX-arg-macro "arg2")
     '("seq_put_right:cn" "arg1" "arg2")
     '("seq_put_right:cV" "arg1" TeX-arg-macro)
     '("seq_put_right:co" "arg1" TeX-arg-macro)
     '("seq_gput_left:Nn" TeX-arg-macro TeX-arg-macro)
     '("seq_gput_left:NV" TeX-arg-macro TeX-arg-macro)
     '("seq_gput_left:No" TeX-arg-macro TeX-arg-macro)
     '("seq_gput_left:Nx" TeX-arg-macro "arg2")
     '("seq_gput_left:cn" "arg1" "arg2")
     '("seq_gput_left:cV" "arg1" TeX-arg-macro)
     '("seq_gput_left:co" "arg1" TeX-arg-macro)
     '("seq_gput_right:Nn" TeX-arg-macro TeX-arg-macro)
     '("seq_gput_right:NV" TeX-arg-macro TeX-arg-macro)
     '("seq_gput_right:No" TeX-arg-macro TeX-arg-macro)
     '("seq_gput_right:Nx" TeX-arg-macro "arg2")
     '("seq_gput_right:cn" "arg1" "arg2")
     '("seq_gput_right:cV" "arg1" TeX-arg-macro)
     '("seq_gput_right:co" "arg1" TeX-arg-macro)
     '("seq_get:NN" TeX-arg-macro TeX-arg-macro)
     '("seq_get:cN" "arg1" TeX-arg-macro)
     '("seq_map_variable:NNn" TeX-arg-macro TeX-arg-macro "code using tl var.")
     '("seq_map_variable:cNn" "arg1" TeX-arg-macro "arg3")
     '("seq_map_function:NN" TeX-arg-macro TeX-arg-macro)
     '("seq_map_function:cN" "arg1" TeX-arg-macro)
     '("seq_map_inline:Nn" TeX-arg-macro "inline function")
     '("seq_map_inline:cn" "arg1" "arg2")
     '("seq_show:N" TeX-arg-macro)
     '("seq_show:c" "arg1")
     '("seq_display:N" TeX-arg-macro)
     '("seq_display:c" "arg1")
     '("seq_remove_duplicates:N" TeX-arg-macro)
     '("seq_gremove_duplicates:N" TeX-arg-macro)
     '("seq_if_empty_p:N" TeX-arg-macro)
     '("seq_if_empty_p:c" "arg1")
     '("seq_if_empty:NT" TeX-arg-macro "true code")
     '("seq_if_empty:NF" TeX-arg-macro "false code")
     '("seq_if_empty:NTF" TeX-arg-macro "true code" "false code")
     '("seq_if_empty:cT" "arg1" "arg2")
     '("seq_if_empty:cF" "arg1" "arg2")
     '("seq_if_empty:cTF" "arg1" "arg2" "arg3")
     '("seq_if_in:NnT" TeX-arg-macro "item" "true code")
     '("seq_if_in:NnF" TeX-arg-macro "item" "false code")
     '("seq_if_in:NnTF" TeX-arg-macro "item" "true code" "false code")
     '("seq_if_in:NVT" TeX-arg-macro TeX-arg-macro "arg3")
     '("seq_if_in:NVF" TeX-arg-macro TeX-arg-macro "arg3")
     '("seq_if_in:NVTF" TeX-arg-macro TeX-arg-macro "arg3" "arg4")
     '("seq_if_in:cnT" "arg1" "arg2" "arg3")
     '("seq_if_in:cnF" "arg1" "arg2" "arg3")
     '("seq_if_in:cnTF" "arg1" "arg2" "arg3" "arg4")
     '("seq_if_in:cVT" "arg1" TeX-arg-macro "arg3")
     '("seq_if_in:cVF" "arg1" TeX-arg-macro "arg3")
     '("seq_if_in:cVTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("seq_if_in:coT" "arg1" TeX-arg-macro "arg3")
     '("seq_if_in:coF" "arg1" TeX-arg-macro "arg3")
     '("seq_if_in:coTF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("seq_if_in:cxT" "arg1" "arg2" "arg3")
     '("seq_if_in:cxF" "arg1" "arg2" "arg3")
     '("seq_if_in:cxTF" "arg1" "arg2" "arg3" "arg4")
     '("seq_if_empty_err:N" TeX-arg-macro)
     '("seq_pop_aux:nnNN" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("seq_push:Nn" TeX-arg-macro "token list")
     '("seq_push:NV" TeX-arg-macro TeX-arg-macro)
     '("seq_push:No" TeX-arg-macro TeX-arg-macro)
     '("seq_push:cn" "arg1" "arg2")
     '("seq_gpush:Nn" TeX-arg-macro "arg2")
     '("seq_gpush:NV" TeX-arg-macro TeX-arg-macro)
     '("seq_gpush:No" TeX-arg-macro TeX-arg-macro)
     '("seq_gpush:Nv" TeX-arg-macro "arg2")
     '("seq_gpush:cn" "arg1" "arg2")
     '("seq_pop:NN" TeX-arg-macro TeX-arg-macro)
     '("seq_pop:cN" "arg1" TeX-arg-macro)
     '("seq_gpop:NN" TeX-arg-macro TeX-arg-macro)
     '("seq_gpop:cN" "arg1" TeX-arg-macro)
     '("seq_top:NN" TeX-arg-macro TeX-arg-macro)
     '("seq_top:cN" "arg1" TeX-arg-macro)
     '("execute_at_document_begin:n" "arg1")
     '("execute_at_document_end:n" "arg1")
     '("execute_at_text_begin:n" "arg1")
     '("execute_at_text_end:n" "arg1")
     "par"
     "g_execute_document_begin_tl"
     "g_execute_document_end_tl"
     "g_execute_text_begin_tl"
     "g_execute_text_end_tl"
     '("iow_new:N" TeX-arg-macro)
     '("iow_new:c" "arg1")
     '("ior_new:N" TeX-arg-macro)
     '("ior_new:c" "arg1")
     "iow_open_streams:"
     "iow_open_streams:"
     '("iow_now:Nx" TeX-arg-macro "tokens")
     '("iow_now:Nn" TeX-arg-macro "arg2")
     '("iow_log:n" "arg1")
     '("iow_log:x" "tokens")
     '("iow_term:n" "arg1")
     '("iow_term:x" "arg1")
     '("iow_now_buffer_safe:Nn" TeX-arg-macro "tokens")
     '("iow_now_buffer_safe:Nx" TeX-arg-macro "arg2")
     '("iow_now_when_avail:Nn" TeX-arg-macro "tokens")
     '("iow_now_when_avail:cn" "arg1" "arg2")
     '("iow_now_when_avail:Nx" TeX-arg-macro "arg2")
     '("iow_now_when_avail:cx" "arg1" "arg2")
     '("iow_shipout:Nx" TeX-arg-macro "tokens")
     '("iow_shipout:Nn" TeX-arg-macro "arg2")
     '("iow_shipout_x:Nx" TeX-arg-macro "tokens")
     '("iow_shipout_x:Nn" TeX-arg-macro "arg2")
     "iow_newline:"
     '("ior_to:NN" TeX-arg-macro TeX-arg-macro)
     '("ior_gto:NN" TeX-arg-macro TeX-arg-macro)
     '("ior_if_eof_p:N" TeX-arg-macro)
     '("ior_if_eof:NT" TeX-arg-macro "true code")
     '("ior_if_eof:NF" TeX-arg-macro "false code")
     '("ior_if_eof:NTF" TeX-arg-macro "true code" "false code")
     '("iow_raw_new:N" TeX-arg-macro)
     '("iow_raw_new:c" "arg1")
     '("ior_raw_new:N" TeX-arg-macro)
     '("ior_raw_new:c" "arg1")
     '("if_eof:w" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     "c_io_streams_tl"
     "c_iow_term_stream"
     "c_ior_term_stream"
     "c_iow_log_stream"
     "c_ior_log_stream"
     "g_iow_streams_prop"
     "g_ior_streams_prop"
     "g_iow_tmp_stream"
     "g_ior_tmp_stream"
     "l_iow_stream_int"
     "l_ior_stream_int"
     '("alloc_new:nnnN" "type" "min" "max" TeX-arg-macro)
     '("alloc_setup_type:nnn" "type" "g_start_num" "l_start_num")
     '("alloc_reg:NnNN" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("alloc_next:Nn" "type")
     '("bool_new:N" TeX-arg-macro)
     '("bool_new:c" "arg1")
     '("bool_set_true:N" TeX-arg-macro)
     '("bool_set_true:c" "arg1")
     '("bool_set_false:N" TeX-arg-macro)
     '("bool_set_false:c" "arg1")
     '("bool_gset_true:N" TeX-arg-macro)
     '("bool_gset_true:c" "arg1")
     '("bool_gset_false:N" TeX-arg-macro)
     '("bool_gset_false:c" "arg1")
     '("bool_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("bool_set_eq:Nc" TeX-arg-macro "arg2")
     '("bool_set_eq:cN" "arg1" TeX-arg-macro)
     '("bool_set_eq:cc" "arg1" "arg2")
     '("bool_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("bool_gset_eq:Nc" TeX-arg-macro "arg2")
     '("bool_gset_eq:cN" "arg1" TeX-arg-macro)
     '("bool_gset_eq:cc" "arg1" "arg2")
     '("bool_not_p:n" "boolean expression")
     '("bool_xor_p:nn" "boolean expression" "boolean expression")
     '("bool_set:Nn" TeX-arg-macro "boolean expression")
     '("bool_set:cn" "arg1" "arg2")
     '("bool_gset:Nn" TeX-arg-macro "arg2")
     '("bool_gset:cn" "arg1" "arg2")
     "mode_if_vertical_p:"
     '("mode_if_vertical:T" "true code")
     '("mode_if_vertical:F" "false code")
     '("mode_if_vertical:TF" "true code" "false code")
     "mode_if_horizontal_p:"
     '("mode_if_horizontal:T" "true code")
     '("mode_if_horizontal:F" "false code")
     '("mode_if_horizontal:TF" "true code" "false code")
     "mode_if_inner_p:"
     '("mode_if_inner:T" "true code")
     '("mode_if_inner:F" "false code")
     '("mode_if_inner:TF" "true code" "false code")
     "mode_if_math_p:"
     '("mode_if_math:T" "true code")
     '("mode_if_math:F" "false code")
     '("mode_if_math:TF" "true code" "false code")
     "scan_align_safe_stop:"
     '("group_align_safe_begin:" TeX-arg-macro)
     "group_align_safe_end:"
     '("prg_replicate:nn" "number" "arg")
     '("prg_quicksort:n" "item~1" "item~2" "item~n")
     '("prg_variable_get_scope:N" TeX-arg-macro)
     '("prg_variable_get_type:N" TeX-arg-macro)
     '("prg_new_map_functions:Nn" TeX-arg-macro "arg2")
     '("prg_set_map_functions:Nn" TeX-arg-macro "arg2")
     "g_prg_inline_level_int"
     '("xref_set_label:n" "name")
     '("xref_new:nn" "type" "value")
     '("xref_deferred_new:nn" "type" "value")
     '("xref_get_value:nn" "type" "name")
     '("xref_define_label:nn" "name" "plist contents")
     "g_xref_all_curr_immediate_fields_prop"
     "g_xref_all_curr_deferred_fields_prop"
     "xref_write"
     '("if_meaning:w" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("if_predicate:w" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("if_bool:N" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("if_mode_horizontal:" TeX-arg-macro TeX-arg-macro)
     "if_mode_vertical:"
     "if_mode_math:"
     "if_mode_inner:"
     '("cs_if_eq_name_p:NN" TeX-arg-macro TeX-arg-macro)
     '("cs_if_do_not_use_p:N" TeX-arg-macro)
     '("chk_if_free_cs:N" TeX-arg-macro)
     '("chk_if_free_cs:c" "arg1")
     '("chk_if_exist_cs:N" TeX-arg-macro)
     '("chk_if_exist_cs:c" "arg1")
     '("str_if_eq_p:nn" "string1" "string2")
     '("str_if_eq_var_p:nf" "string1" "string2")
     '("cs:w" TeX-arg-macro)
     "cs_end:"
     '("use:n" "arg")
     '("use:nn" "arg1" "arg2")
     '("use:nnn" "arg1" "arg2" "arg3")
     '("use:nnnn" "arg1" "arg2" "arg3" "arg4")
     '("use:c" "cs")
     '("use:x" "expandable tokens")
     '("use_i:nn" "code1" "code2")
     '("use_ii:nn" "arg1" "arg2")
     '("use_i:nnn" "arg1" "arg2" "arg3")
     '("use_ii:nnn" "arg1" "arg2" "arg3")
     '("use_iii:nnn" "arg1" "arg2" "arg3")
     '("use_i:nnnn" "arg1" "arg2" "arg3" "arg4")
     '("use_ii:nnnn" "arg1" "arg2" "arg3" "arg4")
     '("use_iii:nnnn" "arg1" "arg2" "arg3" "arg4")
     '("use_iv:nnnn" "arg1" "arg2" "arg3" "arg4")
     '("use_i_ii:nnn" "arg1" "arg2" "arg3")
     '("use_none_delimit_by_q_nil:w" TeX-arg-macro)
     "use_none_delimit_by_q_stop:w"
     "use_none_delimit_by_q_recursion_stop:w"
     '("use_i_delimit_by_q_nil:nw" "arg" TeX-arg-macro)
     "use_i_delimit_by_q_stop:nw"
     "use_i_delimit_by_q_recursion_stop:nw"
     '("exp_after:wN" TeX-arg-macro TeX-arg-macro)
     '("msg_kernel_bug:x" "message")
     '("cs_new:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_new:Npx"
     "cs_new:cpn"
     "cs_new:cpx"
     '("cs_new_nopar:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_new_nopar:Npx"
     "cs_new_nopar:cpn"
     "cs_new_nopar:cpx"
     '("cs_new_protected:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_new_protected:Npx"
     "cs_new_protected:cpn"
     "cs_new_protected:cpx"
     '("cs_new_protected_nopar:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_new_protected_nopar:Npx"
     "cs_new_protected_nopar:cpn"
     "cs_new_protected_nopar:cpx"
     '("cs_new:Nn" TeX-arg-macro "code")
     '("cs_new:Nx" TeX-arg-macro "arg2")
     '("cs_new:cn" "arg1" "arg2")
     '("cs_new:cx" "arg1" "arg2")
     '("cs_new_nopar:Nn" TeX-arg-macro "code")
     '("cs_new_nopar:Nx" TeX-arg-macro "arg2")
     '("cs_new_nopar:cn" "arg1" "arg2")
     '("cs_new_nopar:cx" "arg1" "arg2")
     '("cs_new_protected:Nn" TeX-arg-macro "code")
     '("cs_new_protected:Nx" TeX-arg-macro "arg2")
     '("cs_new_protected:cn" "arg1" "arg2")
     '("cs_new_protected:cx" "arg1" "arg2")
     '("cs_new_protected_nopar:Nn" TeX-arg-macro "code")
     '("cs_new_protected_nopar:Nx" TeX-arg-macro "arg2")
     '("cs_new_protected_nopar:cn" "arg1" "arg2")
     '("cs_new_protected_nopar:cx" "arg1" "arg2")
     '("cs_set:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_set:Npx"
     "cs_set:cpn"
     "cs_set:cpx"
     '("cs_gset:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_gset:Npx"
     "cs_gset:cpn"
     "cs_gset:cpx"
     '("cs_set_nopar:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_set_nopar:Npx"
     "cs_set_nopar:cpn"
     "cs_set_nopar:cpx"
     '("cs_gset_nopar:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_gset_nopar:Npx"
     "cs_gset_nopar:cpn"
     "cs_gset_nopar:cpx"
     '("cs_set_protected:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_set_protected:Npx"
     "cs_set_protected:cpn"
     "cs_set_protected:cpx"
     '("cs_gset_protected:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_gset_protected:Npx"
     "cs_gset_protected:cpn"
     "cs_gset_protected:cpx"
     '("cs_set_protected_nopar:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_set_protected_nopar:Npx"
     "cs_set_protected_nopar:cpn"
     "cs_set_protected_nopar:cpx"
     '("cs_gset_protected_nopar:Npn" TeX-arg-macro TeX-arg-macro "code")
     "cs_gset_protected_nopar:Npx"
     "cs_gset_protected_nopar:cpn"
     "cs_gset_protected_nopar:cpx"
     '("cs_set:Nn" TeX-arg-macro "code")
     '("cs_set:Nx" TeX-arg-macro "arg2")
     '("cs_set:cn" "arg1" "arg2")
     '("cs_set:cx" "arg1" "arg2")
     '("cs_gset:Nn" TeX-arg-macro "code")
     '("cs_gset:Nx" TeX-arg-macro "arg2")
     '("cs_gset:cn" "arg1" "arg2")
     '("cs_gset:cx" "arg1" "arg2")
     '("cs_set_nopar:Nn" TeX-arg-macro "code")
     '("cs_set_nopar:Nx" TeX-arg-macro "arg2")
     '("cs_set_nopar:cn" "arg1" "arg2")
     '("cs_set_nopar:cx" "arg1" "arg2")
     '("cs_gset_nopar:Nn" TeX-arg-macro "code")
     '("cs_gset_nopar:Nx" TeX-arg-macro "arg2")
     '("cs_gset_nopar:cn" "arg1" "arg2")
     '("cs_gset_nopar:cx" "arg1" "arg2")
     '("cs_set_protected:Nn" TeX-arg-macro "code")
     '("cs_set_protected:cn" "arg1" "arg2")
     '("cs_set_protected:Nx" TeX-arg-macro "arg2")
     '("cs_set_protected:cx" "arg1" "arg2")
     '("cs_gset_protected:Nn" TeX-arg-macro "code")
     '("cs_gset_protected:cn" "arg1" "arg2")
     '("cs_gset_protected:Nx" TeX-arg-macro "arg2")
     '("cs_gset_protected:cx" "arg1" "arg2")
     '("cs_set_protected_nopar:Nn" TeX-arg-macro "code")
     '("cs_set_protected_nopar:cn" "arg1" "arg2")
     '("cs_set_protected_nopar:Nx" TeX-arg-macro "arg2")
     '("cs_set_protected_nopar:cx" "arg1" "arg2")
     '("cs_gset_protected_nopar:Nn" TeX-arg-macro "code")
     '("cs_gset_protected_nopar:cn" "arg1" "arg2")
     '("cs_gset_protected_nopar:Nx" TeX-arg-macro "arg2")
     '("cs_gset_protected_nopar:cx" "arg1" "arg2")
     '("cs_undefine:N" TeX-arg-macro)
     '("cs_undefine:c" "arg1")
     '("cs_gundefine:N" TeX-arg-macro)
     '("cs_gundefine:c" "arg1")
     '("cs_new_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("cs_new_eq:cN" "arg1" TeX-arg-macro)
     '("cs_new_eq:Nc" TeX-arg-macro "arg2")
     '("cs_new_eq:cc" "arg1" "arg2")
     '("cs_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("cs_set_eq:cN" TeX-arg-macro TeX-arg-macro)
     '("cs_set_eq:Nc" TeX-arg-macro "arg2")
     '("cs_set_eq:cc" "arg1" "arg2")
     '("cs_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("cs_gset_eq:cN" "arg1" TeX-arg-macro)
     '("cs_gset_eq:Nc" TeX-arg-macro "arg2")
     '("cs_gset_eq:cc" "arg1" "arg2")
     '("cs_to_str:N" TeX-arg-macro)
     '("token_to_str:N" TeX-arg-macro)
     '("token_to_str:c" "arg1")
     '("token_to_meaning:N" TeX-arg-macro)
     '("cs_get_function_name:N" TeX-arg-macro TeX-arg-macro)
     '("cs_get_function_signature:N" TeX-arg-macro)
     '("cs_split_function:NN" TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("cs_get_arg_count_from_signature:N" TeX-arg-macro TeX-arg-macro)
     "scan_stop:"
     '("group_begin:" TeX-arg-macro)
     "group_end:"
     '("group_execute_after:N" TeX-arg-macro)
     '("xetex_if_engine:T" "true code")
     '("xetex_if_engine:F" "false code")
     '("xetex_if_engine:TF" "true code" "false code")
     '("luatex_if_engine:T" "true code")
     '("luatex_if_engine:F" "false code")
     '("luatex_if_engine:TF" "true code" "false code")
     "c_true_bool"
     "c_false_bool"
     "c_minus_one"
     "c_zero"
     "c_sixteen"
     "c_xetex_is_engine_bool"
     "c_luatex_is_engine_bool"
     '("chk_var_or_const:N" TeX-arg-macro)
     '("chk_local:N" TeX-arg-macro)
     '("chk_global:N" TeX-arg-macro)
     '("intexpr_eval:n" "int~expr")
     '("intexpr_compare_p:nNn" "int~expr1" TeX-arg-macro "int~expr2")
     '("intexpr_compare:nNnT" "arg1" TeX-arg-macro "arg3" "arg4")
     '("intexpr_compare:nNnF" "arg1" TeX-arg-macro "arg3" "arg4")
     '("intexpr_compare:nNnTF" "arg1" TeX-arg-macro "arg3" "arg4" "arg5")
     '("intexpr_max:nn" "int~expr1" "int~expr2")
     '("intexpr_min:nn" "arg1" "arg2")
     '("intexpr_abs:n" "int~expr")
     '("intexpr_if_odd:nT" "int~expr" "true")
     '("intexpr_if_odd:nF" "int~expr" "false")
     '("intexpr_if_odd:nTF" "int~expr" "true" "false")
     '("intexpr_if_odd_p:n" "arg1")
     '("intexpr_if_even:nT" "arg1" "arg2")
     '("intexpr_if_even:nF" "arg1" "arg2")
     '("intexpr_if_even:nTF" "arg1" "arg2" "arg3")
     '("intexpr_if_even_p:n" "arg1")
     '("if_num:w" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     "if_inexpr_compare:w"
     '("intexpr_eval:w" TeX-arg-macro)
     "intexpr_eval_end:"
     '("intexpr_while_do:nn" "<int~expr1> <rel> <int~expr2>" "code")
     '("intexpr_until_do:nn" "arg1" "arg2")
     '("intexpr_do_while:nn" "arg1" "arg2")
     '("intexpr_do_until:nn" "arg1" "arg2")
     '("intexpr_while_do:nNnn" TeX-arg-macro TeX-arg-macro TeX-arg-macro "code")
     '("intexpr_until_do:nNnn" "arg1" TeX-arg-macro "arg3" "arg4")
     '("intexpr_do_while:nNnn" "arg1" TeX-arg-macro "arg3" "arg4")
     '("intexpr_do_until:nNnn" "arg1" TeX-arg-macro "arg3" "arg4")
     '("file_if_exist:nT" "arg1" "arg2")
     '("file_if_exist:nF" "arg1" "arg2")
     '("file_if_exist:nTF" "arg1" "arg2" "arg3")
     '("file_if_exist:VT" TeX-arg-macro "arg2")
     '("file_if_exist:VF" TeX-arg-macro "arg2")
     '("file_if_exist:VTF" TeX-arg-macro "arg2" "arg3")
     '("file_input:n" "arg1")
     '("file_input:V" TeX-arg-macro)
     '("file_path_include:n" "arg1")
     '("file_path_remove:n" "arg1")
     "file_list:"
     "g_file_current_name_tl"
     '("num_new:N" TeX-arg-macro)
     '("num_new:c" "arg1")
     '("num_incr:N" TeX-arg-macro)
     '("num_incr:c" "arg1")
     '("num_gincr:N" TeX-arg-macro)
     '("num_gincr:c" "arg1")
     '("num_decr:N" TeX-arg-macro)
     '("num_decr:c" "arg1")
     '("num_gdecr:N" TeX-arg-macro)
     '("num_gdecr:c" "arg1")
     '("num_zero:N" TeX-arg-macro)
     '("num_zero:c" "arg1")
     '("num_gzero:N" TeX-arg-macro)
     '("num_gzero:c" "arg1")
     '("num_set:Nn" TeX-arg-macro "integer")
     '("num_set:cn" "arg1" "arg2")
     '("num_gset:Nn" TeX-arg-macro "arg2")
     '("num_gset:cn" "arg1" "arg2")
     '("num_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("num_set_eq:cN" "arg1" TeX-arg-macro)
     '("num_set_eq:Nc" TeX-arg-macro "arg2")
     '("num_set_eq:cc" "arg1" "arg2")
     '("num_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("num_gset_eq:cN" "arg1" TeX-arg-macro)
     '("num_gset_eq:Nc" TeX-arg-macro "arg2")
     '("num_gset_eq:cc" "arg1" "arg2")
     '("num_add:Nn" TeX-arg-macro "integer")
     '("num_add:cn" "arg1" "arg2")
     '("num_gadd:Nn" TeX-arg-macro "arg2")
     '("num_gadd:cn" "arg1" "arg2")
     '("num_use:N" TeX-arg-macro)
     '("num_use:c" "arg1")
     '("num_show:N" TeX-arg-macro)
     '("num_show:c" "arg1")
     '("if_num:w" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     "c_max_register_num"
     "l_tmpa_num"
     "l_tmpb_num"
     "l_tmpc_num"
     "g_tmpa_num"
     "g_tmpb_num"
     '("lua_now:x" "arg1")
     '("lua_shipout:x" "arg1")
     '("cctab_new:N" TeX-arg-macro)
     '("cctab_begin:N" TeX-arg-macro)
     "cctab_end:"
     "c_code_cctab"
     "c_document_cctab"
     "c_initex_cctab"
     "c_other_cctab"
     "c_string_cctab"
     '("keys_define:nn" "module" "keyval list")
     '("bool_set:N" TeX-arg-macro)
     '("bool_gset:N" TeX-arg-macro)
     "choice:"
     '("choice_code:n" "arg1")
     '("choice_code:x" "arg1")
     '("code:n" "arg1")
     '("code:x" "arg1")
     '("default:n" "arg1")
     '("default:V" TeX-arg-macro)
     '("dim_set:N" TeX-arg-macro)
     '("dim_set:c" "arg1")
     '("dim_gset:N" TeX-arg-macro)
     '("dim_gset:c" "arg1")
     '("generate_choices:n" "arg1")
     '("int_set:N" TeX-arg-macro)
     '("int_set:c" "arg1")
     '("int_gset:N" TeX-arg-macro)
     '("int_gset:c" "arg1")
     '("meta:n" "arg1")
     '("meta:x" "arg1")
     '("skip_set:N" TeX-arg-macro)
     '("skip_set:c" "arg1")
     '("skip_gset:N" TeX-arg-macro)
     '("skip_gset:c" "arg1")
     '("tl_set:N" TeX-arg-macro)
     '("tl_set:c" "arg1")
     '("tl_set_x:N" TeX-arg-macro)
     '("tl_set_x:c" "arg1")
     '("tl_gset:N" TeX-arg-macro)
     '("tl_gset:c" "arg1")
     '("tl_gset_x:N" TeX-arg-macro)
     '("tl_gset_x:c" "arg1")
     "value_forbidden:"
     "value_required:"
     '("keys_set:nn" "module" "keyval list")
     '("keys_set:nV" "arg1" TeX-arg-macro)
     '("keys_set:nv" "arg1" "arg2")
     '("keys_show:nn" "module" "key")
     '("keys_bool_set:NN" TeX-arg-macro TeX-arg-macro)
     '("keys_choice_code_store:x" TeX-arg-macro)
     "keys_choice_make:"
     '("keys_choices_generate:n" "comma list")
     '("keys_choice_find:n" "choice")
     '("keys_cmd_set:nn" "path" "code")
     '("keys_cmd_set:nx" "arg1" "arg2")
     '("keys_default_set:n" "default")
     '("keys_default_set:V" TeX-arg-macro)
     '("keys_define_elt:n" "arg1")
     '("keys_define_elt:nn" "key" "value")
     '("keys_define_key:n" "key")
     "keys_execute:"
     "keys_execute_unknown:"
     '("keys_meta_make:n" "keys")
     '("keys_meta_make:x" "arg1")
     '("keys_property_find:n" "key")
     '("keys_property_new:nn" "property" "code")
     '("keys_property_new_arg:nn" "arg1" "arg2")
     '("keys_property_undefine:n" "property")
     '("keys_set_elt:n" "arg1")
     '("keys_set_elt:nn" "key" "value")
     '("keys_tmp:w" TeX-arg-macro)
     '("keys_value_or_default:n" "value")
     '("keys_value_requirement:n" "requirement")
     '("keys_variable_set:NnNN" TeX-arg-macro TeX-arg-macro TeX-arg-macro TeX-arg-macro)
     '("keys_variable_set:cnNN" "arg1" "arg2" TeX-arg-macro TeX-arg-macro)
     "l_keys_choice_int"
     "l_keys_choice_tl"
     "l_keys_key_tl"
     "c_keys_properties_root_tl"
     "c_keys_root_tl"
     "c_keys_value_forbidden_tl"
     "c_keys_value_required_tl"
     "l_keys_choice_code_tl"
     "l_keys_module_tl"
     "l_keys_path_tl"
     "l_keys_property_tl"
     "l_keys_no_value_bool"
     "l_keys_value_tl"
     "ist_of"
     "unctions"
     "ist_of"
     "unctions"
     '("example_foo:N" TeX-arg-macro)
     '("example_foo:c" "arg1")
     "foo"
     "foo:"
     '("foo:x" "arg1")
     "barrz:"
     "bar"
     "bar:"
     '("bar:x" "arg1")
     '("box_new:N" TeX-arg-macro)
     '("box_new:c" "arg1")
     '("box_if_horizontal_p:N" TeX-arg-macro)
     '("box_if_horizontal_p:c" "arg1")
     '("box_if_horizontal:NT" TeX-arg-macro "true code")
     '("box_if_horizontal:NF" TeX-arg-macro "false code")
     '("box_if_horizontal:NTF" TeX-arg-macro "true code" "false code")
     '("box_if_horizontal:cT" "arg1" "arg2")
     '("box_if_horizontal:cF" "arg1" "arg2")
     '("box_if_horizontal:cTF" "arg1" "arg2" "arg3")
     '("box_if_vertical_p:N" TeX-arg-macro)
     '("box_if_vertical_p:c" "arg1")
     '("box_if_vertical:NT" TeX-arg-macro "true code")
     '("box_if_vertical:NF" TeX-arg-macro "false code")
     '("box_if_vertical:NTF" TeX-arg-macro "true code" "false code")
     '("box_if_vertical:cT" "arg1" "arg2")
     '("box_if_vertical:cF" "arg1" "arg2")
     '("box_if_vertical:cTF" "arg1" "arg2" "arg3")
     '("box_if_empty_p:N" TeX-arg-macro)
     '("box_if_empty_p:c" "arg1")
     '("box_if_empty:NT" TeX-arg-macro "true code")
     '("box_if_empty:NF" TeX-arg-macro "false code")
     '("box_if_empty:NTF" TeX-arg-macro "true code" "false code")
     '("box_if_empty:cT" "arg1" "arg2")
     '("box_if_empty:cF" "arg1" "arg2")
     '("box_if_empty:cTF" "arg1" "arg2" "arg3")
     '("box_set_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("box_set_eq:cN" "arg1" TeX-arg-macro)
     '("box_set_eq:Nc" TeX-arg-macro "arg2")
     '("box_set_eq:cc" "arg1" "arg2")
     '("box_set_eq_clear:NN" TeX-arg-macro TeX-arg-macro)
     '("box_set_eq_clear:cN" "arg1" TeX-arg-macro)
     '("box_set_eq_clear:Nc" TeX-arg-macro "arg2")
     '("box_set_eq_clear:cc" "arg1" "arg2")
     '("box_gset_eq:NN" TeX-arg-macro TeX-arg-macro)
     '("box_gset_eq:cN" "arg1" TeX-arg-macro)
     '("box_gset_eq:Nc" TeX-arg-macro "arg2")
     '("box_gset_eq:cc" "arg1" "arg2")
     '("box_gset_eq_clear:NN" TeX-arg-macro TeX-arg-macro)
     '("box_gset_eq_clear:cN" "arg1" TeX-arg-macro)
     '("box_gset_eq_clear:Nc" TeX-arg-macro "arg2")
     '("box_gset_eq_clear:cc" "arg1" "arg2")
     '("box_set_to_last:N" TeX-arg-macro)
     '("box_set_to_last:c" "arg1")
     '("box_gset_to_last:N" TeX-arg-macro)
     '("box_gset_to_last:c" "arg1")
     '("box_move_right:nn" "arg1" "arg2")
     '("box_move_left:nn" "dimen" "box function")
     '("box_move_up:nn" "arg1" "arg2")
     '("box_move_down:nn" "arg1" "arg2")
     '("box_clear:N" TeX-arg-macro)
     '("box_clear:c" "arg1")
     '("box_gclear:N" TeX-arg-macro)
     '("box_gclear:c" "arg1")
     '("box_ht:N" TeX-arg-macro)
     '("box_ht:c" "arg1")
     '("box_dp:N" TeX-arg-macro)
     '("box_dp:c" "arg1")
     '("box_wd:N" TeX-arg-macro)
     '("box_wd:c" "arg1")
     '("box_show:N" TeX-arg-macro)
     '("box_show:c" "arg1")
     '("hbox:n" "contents")
     '("hbox_set:Nn" TeX-arg-macro "contents")
     '("hbox_set:cn" "arg1" "arg2")
     '("hbox_gset:Nn" TeX-arg-macro "arg2")
     '("hbox_gset:cn" "arg1" "arg2")
     '("hbox_set_to_wd:Nnn" TeX-arg-macro "dimen" "contents")
     '("hbox_set_to_wd:cnn" "arg1" "arg2" "arg3")
     '("hbox_gset_to_wd:Nnn" TeX-arg-macro "arg2" "arg3")
     '("hbox_gset_to_wd:cnn" "arg1" "arg2" "arg3")
     '("hbox_overlap_left:n" TeX-arg-macro)
     '("hbox_overlap_right:n" "arg1")
     '("hbox_unpack:N" TeX-arg-macro)
     '("hbox_unpack:c" "arg1")
     '("hbox_unpack_clear:N" TeX-arg-macro)
     '("hbox_unpack_clear:c" "arg1")
     '("vbox:n" "contents")
     '("vbox_top:n" "contents")
     '("vbox_set:Nn" TeX-arg-macro "contents")
     '("vbox_set:cn" "arg1" "arg2")
     '("vbox_gset:Nn" TeX-arg-macro "arg2")
     '("vbox_gset:cn" "arg1" "arg2")
     '("vbox_set_top:Nn" TeX-arg-macro "contents")
     '("vbox_set_top:cn" "arg1" "arg2")
     '("vbox_gset_top:Nn" TeX-arg-macro "arg2")
     '("vbox_gset_top:cn" "arg1" "arg2")
     '("vbox_set_to_ht:Nnn" TeX-arg-macro "dimen" "contents")
     '("vbox_set_to_ht:cnn" "arg1" "arg2" "arg3")
     '("vbox_gset_to_ht:Nnn" TeX-arg-macro "arg2" "arg3")
     '("vbox_gset_to_ht:cnn" "arg1" "arg2" "arg3")
     '("vbox_gset_to_ht:ccn" "arg1" "arg2" "arg3")
     '("vbox_set_split_to_ht:NNn" TeX-arg-macro TeX-arg-macro "dimen")
     '("vbox_unpack:N" TeX-arg-macro)
     '("vbox_unpack:c" "arg1")
     '("vbox_unpack_clear:N" TeX-arg-macro)
     '("vbox_unpack_clear:c" "arg1")
     "c_empty_box"
     "l_tmpa_box"
     "l_tmpb_box"
     "l_last_box"
     "c_format_name"
     "c_format_date"
     '("msg_class_new:nn" "arg1" "arg2")
     '("msg_class_set:nn" "arg1" "arg2")
     '("msg_redirect_class:nn" "arg1" "arg2")
     '("msg_redirect_name:nnn" "arg1" "arg2" "arg3")
     "msg_line_context:"
     "msg_line_number:"
     "msg_newline:"
     "msg_two_newlines:"
     '("msg_generic_new:nnn" "arg1" "arg2" "arg3")
     '("msg_generic_new:nn" "arg1" "arg2")
     '("msg_generic_set:nnn" "arg1" "arg2" "arg3")
     '("msg_generic_set:nn" "arg1" "arg2")
     '("msg_direct_log:xx" "arg1" "arg2")
     '("msg_direct_term:xx" "arg1" "arg2")
     '("msg_kernel_bug:x" "arg1")
     "c_msg_fatal_tl"
     "c_msg_error_tl"
     "c_msg_warning_tl"
     "c_msg_info_tl"
     "c_msg_coding_error_text_tl"
     "c_msg_fatal_text_tl"
     "c_msg_help_text_tl"
     "c_msg_kernel_bug_text_tl"
     "c_msg_kernel_bug_more_text_tl"
     "c_msg_no_info_text_tl"
     "c_msg_return_text_tl"
     "c_msg_on_line_tl"
     "c_msg_text_prefix_tl"
     "c_msg_more_text_prefix_tl"
     "l_msg_class_tl"
     "l_msg_current_class_tl"
     "l_msg_current_module_tl"
     "l_msg_names_clist"
     "l_msg_redirect_classes_prop"
     "l_msg_redirect_names_prop"
     "l_msg_redirect_classes_clist"))))
